from content.host_guides import guide

guide('comfort', 'linen-par-stock-calculation', 'Calculate Linen Par Stock from Your Laundry Cycle', 'Estimate sheet and towel sets from installed beds, changeovers, laundry turnaround, spares, and clean storage capacity.',
'''Linen par stock is the quantity needed to keep the property supplied while used items are being washed or held aside. A fixed rule of “three sets” may be a useful starting thought, but the right quantity depends on the laundry process, turnover pattern, losses, and storage available at this property.''',
'''Define one set precisely before doing arithmetic. For a bed, specify sheet sizes, pillowcase quantity, and any cover included in the reset. Towels need a separate calculation based on the actual supplied allocation. Count the sets installed, the sets required for upcoming resets before laundry returns, and a separately stated spare allowance.

Map collection and return times with the laundry provider. Clean stock must be ready before it is needed, not merely expected back later that afternoon. Do not treat dirty, stained, incompatible, or damp items as available sets. Check storage size and handling so extra stock can remain clean, dry, and identifiable.''',
'''Hypothetical sheet plan: three beds each need one installed set, totaling three. The laundry process can leave one full changeover of three sets away at once. One additional set per bed is held as an assumed contingency, adding three. The total is nine complete sets. If two changeovers can occur before returns, the working stock changes: three installed plus six away plus three spare equals twelve. These quantities illustrate the method rather than prescribing stock for every rental.''',
'''Define a complete set by bed size and actual reset specification, including pillowcases and covers where supplied.
Map the laundry collection, processing, return, and storage cycle against possible changeover timing.
Calculate installed stock, working-cycle stock, and contingency separately so each assumption is visible.
Exclude unsuitable, incomplete, damp, or damaged items from the available clean count.
Check storage capacity and label sets so the cleaner can quickly select the correct size and version.''',
'''Reconcile physical stock regularly and record losses or repeated shortages by item. If pillowcases disappear faster than sheets, buy the missing component rather than automatically purchasing whole sets. Adjust the assumed contingency from actual experience. A larger par quantity cannot solve unreliable returns or inadequate drying; fix the process as well as the count.''', ['shopping','moisture'])

guide('comfort', 'bedding-fit-system-check', 'Check Mattress, Protector and Linen Fit as One System', 'Trial the complete bed setup for dimensions, mattress depth, protector fit, cover sizing, making time, and replacement compatibility.',
'''Mattress, frame, protector, fitted sheet, and cover are often purchased from different suppliers. Each can be correct on its own while the combined bed is awkward to make or uncomfortable to use. Build one complete trial bed before ordering every linen set for the property.''',
'''Record the actual mattress dimensions and depth, including a topper if one is used. Check the base and mattress instructions together. Choose protectors and linens from verified size information rather than relying only on names such as queen or deep pocket. International sizing, product tolerances, and different cover proportions can create mismatches.

Have the cleaner make the bed using the proposed process and inspect how each layer sits. Corners should fit as intended, covers should stay properly positioned, and the reset should not depend on forcing an undersized sheet. Review the product’s washing and drying instructions before approving a large quantity. Test laundering where the supplier permits it, remembering that return terms may change once textiles are used or washed.''',
'''Hypothetical sample: a queen mattress with a topper is deeper than the original fitted-sheet specification. The sheet repeatedly releases at one corner during the trial. The owner checks the actual depth and orders a properly specified sample instead of assuming the mattress is the problem. A duvet cover also fits poorly, so its dimensions are checked against the insert before the remaining bedroom orders are released.''',
'''Measure the installed mattress and any topper rather than using only the nominal bed-size name.
Check frame, base, and mattress compatibility using the actual product instructions.
Make a complete trial bed with protector, sheets, pillows, inserts, and covers selected for the property.
Confirm laundering instructions, practical handling, and the effect on any return conditions before testing textiles.
Record exact sizes and models in the linen inventory so later replacements match the installed system.''',
'''Approve the system after the cleaner and trial-stay tester have used it. Record any special making instructions concisely. If a mattress, topper, insert, or protector changes later, repeat the relevant fit check; the prior linen approval may no longer hold. Keep incompatible stock separate so it does not return to a guest bed during a rushed reset.''', ['shopping','warranty'])

guide('comfort', 'pillow-options-storage', 'Offer Pillow Options with a Clear Reset and Storage Plan', 'Plan a manageable pillow assortment using exact care instructions, clean storage, labeling, and an accurate bedroom reset.',
'''Guests have different pillow preferences, but an uncontrolled assortment can create storage and cleaning problems. If you offer options, keep the choices understandable and the maintenance process clear. A few supported products are more useful than a closet filled with unidentified pillows of uncertain condition.''',
'''Choose the baseline bed setup and any optional alternative, then document exact models, sizes, materials, protectors, and care instructions. Avoid making allergy-free or medical claims without appropriate evidence. A material description should reflect the product label. Keep extra pillows protected and separate from used textiles; a pillow placed back in a closet after use is not automatically ready for the next guest.

Define how a guest accesses the optional item and how the cleaner identifies what needs resetting. The team should be able to inspect condition and follow the appropriate cleaning process for each version. If the laundry system cannot support an option, reconsider it before adding more stock.''',
'''Hypothetical bedroom: the standard setup uses two matching pillows per sleeper. One clearly identified alternative pair is stored in clean protective covers on a dedicated shelf. The reset guide shows the baseline and the optional location. After a stay, the cleaner inspects both locations and follows each product’s care process. No label promises a particular sleep result; the purpose is to make the choice understandable and maintainable.''',
'''Specify the baseline quantity and optional assortment without exceeding the storage and cleaning capacity of the room.
Record model, size, fill description, protectors, and exact care instructions for each option.
Create clean, dry storage that separates available extras from used or uncertain-condition pillows.
Tell the reset team how to inspect and restore both the bed setup and the optional storage location.
Use accurate material descriptions and avoid unsupported medical, allergy, or universal-comfort claims.''',
'''Review actual use and maintenance feedback before expanding the assortment. Replace damaged or unsuitable pillows through the inventory process and keep the matching cases and protectors organized. If an option is removed, update the guest guide and reset photograph. The value comes from a reliable choice guests can understand, not from a large number of pillows in the listing photo.''', ['shopping','warranty'])

guide('comfort', 'bedroom-noise-observation-log', 'Keep a Bedroom Noise Observation Log Before Styling', 'Record nighttime noise sources, timing, room use, and practical furnishing responses without promising soundproofing.',
'''Soft textiles can change how a room feels, but they do not automatically block noise from outside or adjoining spaces. Before buying furnishings to solve a noise complaint, record what is heard, when it occurs, and where it seems to enter. A useful log separates observations from assumptions about the cause.''',
'''Listen from the sleeping position in ordinary nighttime conditions. Note traffic, doors, appliances, loose hardware, or sound from shared spaces. Record whether a source is continuous, intermittent, or associated with a particular activity. Avoid collecting conversations or using monitoring equipment without the appropriate operating review and policies; simple observation can answer many furnishing questions.

Fix basic mechanical issues through maintenance before adding décor. A loose bed component, rattling fan cover, or door latch may need repair. For building transmission or complex acoustic problems, obtain specialist advice. Rugs, curtains, and upholstered surfaces may help with room reflections, but describe them as furnishing choices rather than certified soundproofing.''',
'''Hypothetical observation: a bedroom seems noisy when the nearby bathroom door closes, while street sound is also audible early in the morning. Maintenance addresses the door hardware with an appropriate repair. The remaining external sound is documented for specialist review and accurate property description. A new rug is selected for the room’s design and reflected-sound comfort, without claiming that it will eliminate traffic noise.''',
'''Record the listening position, date, approximate time, weather where relevant, and ordinary room conditions.
Describe each source and its timing without assuming the path or cause is established.
Inspect loose furniture or fixtures and assign mechanical issues to maintenance or the appropriate specialist.
Trial furnishing changes only for the problem they can reasonably address and keep observations before and after.
Describe the property accurately and avoid promising silence or soundproofing from decorative materials alone.''',
'''Revisit the log after repairs and during a trial stay. If a change appears useful, confirm it under comparable conditions instead of drawing a conclusion from a single quiet night. Keep technical work and guest-description updates with the responsible owner. The log guides investigation and decisions; it is not an acoustic certification or a health assessment.''', ['warranty'])

guide('comfort', 'charging-and-personal-items', 'Plan Charging and Personal-Item Space from the Guest’s Seat', 'Check power access, phone surfaces, cord routing, bedside reach, and reset instructions without adding unnecessary devices.',
'''Guests need a place to set a phone, glasses, a book, or a small bag as much as they need a charging point. Test those details from the seat and bed rather than locating power wherever it is easiest to hide in a photograph. The best arrangement may require a furniture change instead of another gadget.''',
'''Identify personal-item surfaces beside the main seating and sleeping positions. Test power reach using ordinary charging equipment, keeping cords out of doors and routes. Confirm product suitability and installation with the responsible professional where electrical changes are needed. Avoid making a permanent setup from an unsuitable temporary extension arrangement.

Keep any supplied charging product identifiable, maintainable, and easy to reset. Device compatibility changes, and a built-in port does not guarantee every guest’s equipment can use it. Provide accurate descriptions and preserve access to ordinary power where appropriate. Do not fill the surface with décor until a guest has nowhere to put their belongings.''',
'''Hypothetical bedside layout: a charging port sits behind a deep table and is hard to reach. A smaller table with a clear top gives the guest room for a phone and water glass, while an appropriate reviewed power arrangement keeps the cord away from the door. The team tests both sides of the bed. The listing describes the actual provision rather than promising universal compatibility with every device.''',
'''Allocate clear personal-item surfaces at the main seating and sleeping positions before adding decorative accessories.
Check charging reach and ordinary cable placement from the positions guests actually use.
Have electrical work and any uncertain product installation reviewed by the responsible professional.
Record the supplied product model, instructions, and replacement process if charging equipment is provided.
Include a simple condition and function check in the reset without making unsupported compatibility claims.''',
'''Keep surfaces and power access visible in the reset photographs. Remove damaged equipment from service through maintenance rather than leaving a warning note beside it. Recheck after a furniture substitution or new bed frame. If guests repeatedly move the table to reach power, treat that behavior as layout feedback and correct the arrangement instead of adding longer cords by default.''', ['recalls','warranty'])

guide('comfort', 'climate-control-guest-brief', 'Make Climate Controls Findable and the Instructions Accurate', 'Coordinate furniture placement, vents, thermostat access, bedding layers, and a concise climate-control handover.',
'''A room’s climate system can be functional while guests struggle to find or understand its controls. Furniture can hide a thermostat, block a vent, or make a simple task awkward. Review the installed room with the property manager before writing climate instructions or adding more blankets and fans.''',
'''Locate controls, supply and return paths, and equipment service access on the room plan. Have any technical questions assessed by the appropriate professional. Keep required access and airflow clear according to equipment guidance. Check that artwork, curtains, wardrobes, and bedside furniture do not conceal the normal control path.

Write instructions from verified operation of the actual system. State the ordinary actions guests can take and the contact route when it does not work. Do not promise that the system can achieve every requested condition or add unverified operating limits. If optional bedding layers are supplied, document their care, clean storage, and reset location.''',
'''Hypothetical bedroom: a curtain panel falls over a vent and a tall cabinet partly hides the control. The designer and responsible technician review the arrangement and revise it. A trial-stay tester follows a short instruction card using the installed controls. The manager corrects a mislabeled mode description before handover. Extra bedding is stored cleanly in a labeled location rather than piled where it obstructs the window treatment.''',
'''Show controls, vents, equipment, and service access on the furniture plan before approving tall or floor-level pieces.
Confirm appropriate clearances and technical operation through equipment guidance and the responsible professional.
Test the ordinary guest control actions on the actual installed system and record clear instructions.
Check curtains and décor in their normal positions so they do not conceal controls or required access.
Provide a maintenance contact and a care/reset plan for any optional climate-related comfort items.''',
'''Update the instructions after a control, system, or furniture change. If guests report persistent discomfort or moisture, investigate the system and conditions rather than assuming additional textiles will solve it. Keep the furnishing review separate from technical commissioning while ensuring the two teams share constraints. Accurate operation and accessible controls are the foundation of the comfort plan.''', ['air','moisture'])

guide('comfort', 'guest-towel-drying-plan', 'Plan Where Every Guest Can Dry a Towel', 'Coordinate towel hooks, rails, spacing, bathroom capacity, installation, and clean-linen separation for the intended guest group.',
'''A rental can provide plenty of towels but too few places to hang them. Guests then use chair backs, wardrobe doors, or the bed, transferring moisture to surfaces that were not designed for it. Plan drying locations alongside the linen quantity and intended guest group.''',
'''Count the supplied towel allocation and the usable hanging locations. Check each hook or rail with a towel in place, including door movement and neighboring items. Two adjacent hooks may not provide two practical drying positions if the towels overlap. Choose suitable hardware, finish, and installation for the load and wall conditions.

Keep clean stock separate from wet towels and give the reset team access to inspect the area behind hanging items. Review moisture and ventilation concerns through the property’s maintenance process. Adding hooks is a furnishing response to storage shortage, not a solution for persistent dampness or inadequate ventilation.''',
'''Hypothetical four-guest rental: a bathroom has one rail, while the guest allocation assumes four bath towels in use. The team trials appropriately spaced hooks in suitable locations and checks them with actual towels. One proposed hook behind the door is removed from the plan because the towel catches when the door opens. Clean spare towels stay on a separate dry shelf. The reset guide records both the supply quantity and the installed hanging arrangement.''',
'''Count the intended towels in use and compare that number with practical drying locations by bathroom or bedroom.
Test actual towels on the proposed hooks or rails with doors and nearby furniture in ordinary positions.
Verify hardware suitability, finish care, load, and appropriate fixing before installation.
Keep clean stock separated from wet towels and provide a defined used-textile handling process.
Ask the cleaner to inspect, clean, and dry the hardware area during a complete reset trial.''',
'''Use guest and cleaner feedback to identify locations that are awkward or regularly unused. Recheck the plan when the guest capacity or towel allocation changes. Loose hardware, damaged walls, or recurring dampness should enter the maintenance process promptly. A complete towel plan covers supply, use, drying, laundry, and storage rather than treating the bathroom photo as the finished specification.''', ['moisture','cleaning'])

guide('comfort', 'first-night-guest-instructions', 'Write First-Night Instructions from a Real Test Stay', 'Create a short arrival-to-bed guide from observed controls, storage, lighting, bedding, and contact needs in the installed property.',
'''A welcome guide can become a list of features the guest does not need on the first night. Write the essential arrival-to-bed instructions from a real walkthrough of the installed property. Focus on the actions a new guest must complete before they can settle in.''',
'''Have a tester unfamiliar with the room enter, set down bags, find useful lights, locate the bathroom, and prepare for sleep. Observe confusion rather than coaching immediately. Record the questions that recur: which switch works, where extra bedding is stored, how curtains operate, or where to put wet towels. Correct the layout or malfunction first, then write instructions for the remaining necessary actions.

Use accurate, short statements and ordinary names that match the labels in the property. Keep private access information and security-sensitive details in the manager’s appropriate guest-delivery process rather than publishing them in a public design article or uncontrolled file. Provide a clear contact route for problems the guest cannot resolve.''',
'''Hypothetical trial: the tester cannot find the bedside lamp switch and looks for extra blankets in owner storage. The lamp is repositioned and the clean blanket location becomes obvious. The resulting guide needs only a short curtain explanation, the climate-control steps, and the help contact. It does not compensate for every design issue with another paragraph. The owner verifies each instruction against the final installed setup before photography and launch.''',
'''Run the arrival-to-bed journey with a tester who does not already know the property’s control layout.
Record confusion and distinguish broken functions, poor placement, and genuinely necessary instructions.
Fix functional or layout issues before writing a workaround into the guest guide.
Use names matching the property and keep confidential access details in the appropriate private operating process.
Verify the final instructions after installation and assign an owner to update them when the setup changes.''',
'''Keep the public listing, guest guide, and cleaner reset consistent about what is provided. Repeat the first-night test after major changes or repeated feedback. Short instructions work best when the room itself is understandable. Save the observations in the commissioning log so the team can see why a control, storage location, or instruction was changed.''', ['shopping'])
