"""Original editorial data for the host planning library. Prices/examples are hypothetical."""

GUIDES = []

def guide(cluster, slug, title, description, intro, decision, example, checklist, handoff, sources):
    GUIDES.append(dict(cluster=cluster, slug=slug, title=title, description=description,
                       intro=intro, decision=decision, example=example,
                       checklist=checklist, handoff=handoff, sources=sources))

SOURCES = {
    'shopping': ('FTC: Online shopping', 'https://consumer.ftc.gov/articles/online-shopping'),
    'warranty': ('FTC: Warranties', 'https://consumer.ftc.gov/articles/warranties'),
    'recalls': ('CPSC: Recalls and product safety warnings', 'https://www.cpsc.gov/Recalls'),
    'anchor': ('CPSC: Anchor It', 'https://www.anchorit.gov/'),
    'cords': ('CPSC: Window covering cords', 'https://www.cpsc.gov/gocordless'),
    'bulbs': ('FTC: Shopping for light bulbs', 'https://consumer.ftc.gov/articles/shopping-light-bulbs'),
    'darksky': ('DarkSky: Responsible outdoor lighting', 'https://darksky.org/resources/guides-and-how-tos/lighting-principles/'),
    'fabric': ('Sunbrella: Fabric care instructions', 'https://www.sunbrella.com/how-to-clean-sunbrella-fabric'),
    'paint': ('Benjamin Moore: Choosing a paint finish', 'https://www.benjaminmoore.com/en-us/interior-exterior-paints-stains/how-to-advice/painting-101/choosing-paint-finish'),
    'moisture': ('EPA: Mold and moisture guide', 'https://www.epa.gov/mold/brief-guide-mold-moisture-and-your-home'),
    'air': ('EPA: Indoor air quality guide', 'https://www.epa.gov/indoor-air-quality-iaq/inside-story-guide-indoor-air-quality'),
    'cleaning': ('EPA: Safer Choice', 'https://www.epa.gov/saferchoice'),
    'routes': ('U.S. Access Board: Accessible routes', 'https://www.access-board.gov/ada/guides/chapter-4-accessible-routes/'),
}

CLUSTERS = {
    'planning': dict(title='Furnishing Budgets and Room Planning', description='Build an itemized furnishing plan, measure the property, and separate purchase costs from delivery, installation, and reserves.', intro='Start with the decisions that determine every purchase: what the property needs, who will use each room, how items will get inside, and how much cash remains after installation. These worksheets help turn a collection of attractive products into a coherent scope.', steps=['Walk the property and record what can remain before setting shopping allowances.', 'Measure rooms and delivery routes; write down the uses each room must support.', 'Price essential items with delivery and installation, then reserve funds before choosing optional upgrades.'], legacy='/faq/budget/'),
    'materials': dict(title='Durable Materials and Repairable Furniture', description='Evaluate furniture construction, fabric care, paint touch-ups, and cleaning capacity before buying furnishings for a rental.', intro='A material decision is also a maintenance decision. Use this collection to compare actual product specifications, request useful samples, and choose details that the people caring for your property can clean or repair. A durability label alone is not a complete specification.', steps=['List the likely spills, moisture, abrasion, and handling in each location.', 'Read the exact product care instructions and test a spare sample where appropriate.', 'Compare replaceable parts, service access, and availability before approving the order.'], legacy='/resources/damage-resistant-materials/index.html'),
    'layouts': dict(title='Rental Layouts and Circulation', description='Plan clear routes, dining seats, luggage storage, work areas, and convertible sleeping spaces around real guest activities.', intro='A room plan should work when guests arrive with bags, move chairs, open doors, and use several activities at once. These guides focus on those conflicts. Use measured mock-ups to judge fit, and obtain professional review where building or accessibility requirements apply.', steps=['Draw fixed constraints first: doors, windows, outlets, vents, and built-ins.', 'Mark travel paths and open furniture positions before adding decorative pieces.', 'Walk the plan with bags, chairs, and cleaning equipment, then document any compromises.'], legacy='/services.html'),
    'lighting': dict(title='Lighting Plans and Window Treatments', description='Specify consistent bulbs, useful controls, glare management, nighttime routes, and window coverage for a rental.', intro='Lighting succeeds when a new guest can immediately see where to go and how to make a room comfortable. Start with activities and controls, then select fixtures. The collection addresses practical specification and testing rather than promising a universal brightness formula.', steps=['Visit during daylight and after dark to record the actual light conditions.', 'Separate arrival, task, relaxation, and cleaning needs on the room plan.', 'Test fixtures, controls, window coverage, and replacement bulbs before photography.'], legacy='/blog/airbnb-lighting-guide.html'),
    'comfort': dict(title='Sleep and Everyday Guest Comfort', description='Plan bedding fit, pillow storage, acoustic comfort, charging access, climate controls, and clear guest instructions.', intro='Comfort comes from details that remain useful after the listing photo is taken. These guides help coordinate beds, textiles, storage, controls, and instructions with the turnover team. Treat trial stays and direct observations as feedback; individual guests will have different preferences.', steps=['Build the bed and test it with the linens, protector, and base together.', 'Try the room at night with the lights off and luggage in place.', 'Document the reset so comfort survives cleaning, laundry, and replacement cycles.'], legacy='/faq/furniture/'),
    'maintenance': dict(title='Cleaning, Maintenance and Replacement Planning', description='Create practical room reset standards, product records, spare inventories, repair decisions, and feedback loops for rental furnishings.', intro='Maintenance planning keeps the design usable. Use this collection to make care instructions easy to find, give each issue an owner, and distinguish a cosmetic refresh from a repair that needs specialist attention. The goal is a repeatable process the local team can carry out.', steps=['Record model numbers and care instructions while the purchase information is available.', 'Test the reset with the people who will clean and maintain the property.', 'Track failures and adjust specifications or spare stock from actual experience.'], legacy='/faq/maintenance/'),
    'outdoors': dict(title='Weather, Outdoor Spaces and Seasonal Storage', description='Plan exposure-aware outdoor furniture, drying and storage routines, shade, salt care, and seasonal furnishing handoffs.', intro='Outdoor furnishings interact with sun, rain, wind, salt, dirt, and the storage space available between stays. Begin with the site conditions and product instructions. These guides turn those observations into a practical furnishing and reset plan without treating any material as weatherproof.', steps=['Observe exposure at the times guests are likely to use the space.', 'Check product suitability and where loose items can be stored or dried.', 'Write a local reset and seasonal handoff before installing furnishings.'], legacy='/resources/seasonal-decor-calendar/index.html'),
    'launch': dict(title='Procurement, Installation and Rental Launch', description='Coordinate vendor quotes, substitutions, deliveries, installation, photography, and a documented furnishing handover.', intro='A furnishing project needs decision owners as much as it needs products. These guides help organize purchasing, receiving, installation, testing, and handover so unresolved details are visible before guests arrive. The sample schedules and allocations are planning examples, not promised delivery times.', steps=['Agree on scope, approval owners, dependencies, and substitution rules.', 'Track orders and prepare the receiving and installation team before dispatch.', 'Close functional issues, test the guest journey, and hand over an accurate inventory.'], legacy='/resources/briefing-designer-str/index.html'),
}

guide('planning', 'scope-before-shopping', 'Write a Furnishing Scope Before You Start Shopping', 'Turn a rental walkthrough into a room-by-room scope with clear inclusions, exclusions, priorities, and approval owners.',
'''A shopping list tells you what to buy. A furnishing scope explains what has to work when the project is finished. Write the scope before browsing products, especially when an owner, designer, installer, and property manager share responsibility. Otherwise each person can assume somebody else is handling the small items that make the property usable.''',
'''Organize the scope by room and activity rather than by retailer. A bedroom needs sleeping, reading, charging, clothes storage, and a place for luggage. Each activity can have a different owner or constraint. Record existing items that stay, items to replace, and missing functions. Mark required repairs separately; a new dresser will not solve a damp wall.

Give every line an acceptance condition. “Two bedside lamps, both operable from bed” is easier to verify than “bedroom styling.” Separate furnishing from electrical work, mounting, receiving, assembly, packaging removal, linen washing, and photography. Ask who supplies hardware and who approves substitutions. Put exclusions beside the relevant room so they do not disappear in a general note at the end.''',
'''Hypothetical scope: a two-bedroom rental retains its dining table and four sound chairs. The living room needs seating for four, a reading light, and a place for bags; it does not need a second decorative console. The owner handles painting before installation. The installer assembles beds and removes cartons. The manager washes the first linen sets. Photography happens only after the room reset is tested. This document makes the handoff visible without claiming a particular price or launch duration.''',
'''Walk every room with the manager and record its essential activities, fixed constraints, and existing furniture condition.
Assign one named approval owner to each purchase category, including small accessories and replacement choices.
Separate trades, receiving, assembly, mounting, disposal, laundry, and styling so each task has a responsible party.
Define the evidence for completion: a measurement, product record, working function, or agreed photograph.
Keep a dated change log with the reason, cost effect, and approval for every scope change.''',
'''Use the final scope to compare quotes on the same basis. If a quote omits receiving or installation, add those costs before comparing totals. At handover, walk the activities rather than counting attractive objects. Any unfinished essential function belongs on a punch list with an owner and target date. Keep the approved scope with the inventory so a later refresh starts from what the property actually needs.''', ['shopping','warranty'])

guide('planning', 'landed-furnishing-cost', 'Calculate the Landed Cost of Rental Furnishings', 'Compare furniture quotes with shipping, receiving, assembly, tax, removal, and a separately stated contingency allowance.',
'''The product price is only one part of getting a usable item into a rental. A sofa with a low advertised price can become the more expensive choice after delivery, stair handling, assembly, or returns. Build a landed-cost worksheet so the selection decision reflects the work your project actually requires.''',
'''Start with item quantity and unit price, then add actual quoted shipping, receiving or storage, installation, and any disposal charge. Include tax using the applicable quote or rate for the delivery location; do not assume a national rate. Check whether a delivery fee covers the room of choice or only a curbside drop. Keep optional service contracts distinct from required charges.

Show contingency as its own planning allowance rather than hiding it inside each item. Do not add tax or delivery twice when they are already included. Record currency, quote date, expiration, and the payment schedule. Compare quotes only after matching the scope: a flat-pack bed needing assembly and a fully installed bed are different deliverables.''',
'''Hypothetical example, using assumed prices and tax solely to demonstrate arithmetic: two chairs at $180 each cost $360. Shipping is $70, assembly is $40, and assumed tax is $36. The landed total is $506, or $253 per installed chair. A second quote of $480 for both chairs delivered and assembled, plus assumed tax of $38.40, totals $518.40. The difference is $12.40. That small gap may matter less than dimensions, replaceable parts, or whether the delivery service can meet the receiving plan.''',
'''Record quantity, model, finish, unit price, and which services the product listing explicitly includes.
Obtain the delivery location surcharge and confirm access limits before treating a shipping estimate as final.
Ask whether receiving, storage, assembly, mounting, and packaging removal are separately priced.
Verify the tax basis, discount treatment, and any refundable deposit with the vendor quote.
Compare the full installed totals and record a separate contingency assumption with its reason.''',
'''Keep estimated and committed totals in separate columns. Replace estimates as written quotes arrive, then reconcile invoices after installation. If a vendor changes the model, rerun the entire line because size, freight, and assembly may change too. This is a purchase-planning exercise; it does not predict bookings or returns from the furnishing investment. Use actual local quotes to set the project budget.''', ['shopping','warranty'])

guide('planning', 'replacement-reserve-worksheet', 'Build a Furnishing Replacement Reserve Worksheet', 'Estimate a rental furnishing reserve from individual replacement scenarios, useful-life assumptions, and real failure records.',
'''A replacement reserve is money held for worn or damaged items after launch. It is separate from cleaning supplies and the original furnishing budget. You do not need to predict each failure perfectly to start a useful worksheet. You do need to show your assumptions and update them when the property provides better evidence.''',
'''List items that would disrupt the guest experience if unavailable: mattresses, bed frames, key seating, curtains, lamps, and small appliances. Enter an estimated replacement cost including delivery and installation. Add a planning interval based on product condition and your operating expectations, clearly marking it as an assumption. Divide the cost by that interval to create an annual allowance; the result is a budgeting convention, not a claim about product lifespan.

Keep accidental damage scenarios in a separate column. Coverage, deposits, and reimbursement processes may not pay the full cost or pay quickly. Ask the relevant provider about actual terms rather than deducting a hoped-for recovery. A spare item can reduce an interruption, but it still ties up cash and requires storage.''',
'''Hypothetical worksheet: a sofa replacement is assumed to cost $1,200 installed after four years, giving $300 a year. Two lamps together cost an assumed $180 after three years, giving $60 a year. A curtain set costs an assumed $300 after five years, giving $60 a year. These three lines total $420 annually, or $35 monthly. They are only a partial inventory. A real reserve would also consider other assets and a separate allowance for unexpected failures.''',
'''Inventory the essential furnishings and flag items with long replacement lead times or unusual dimensions.
Record installed replacement cost, condition, planning interval, and where each estimate came from.
Calculate annual allowances per line, then sum them without presenting the interval as a warranty.
List damage scenarios and any coverage questions separately from normal wear assumptions.
Review the worksheet after actual replacements and during the property’s scheduled condition review.''',
'''After a failure, record age, cause, downtime, repair cost, and whether a different specification would have helped. Keep cosmetic updates separate from necessary replacements so style preferences do not consume the entire reserve. If your records show cushions wear while the frame remains sound, model cushion replacement separately. The reserve should become more specific over time, using this property’s experience rather than an unsupported industry percentage.''', ['warranty'])

guide('planning', 'phased-furnishing-plan', 'Phase a Rental Refresh Around Essential Guest Functions', 'Sequence a furnishing refresh by guest function, dependencies, storage, and access rather than buying everything at once.',
'''A phased refresh can make a large project manageable, but only when each phase leaves a complete and accurately represented guest experience. Dividing purchases into arbitrary monthly spending blocks can produce a room with new art and an unusable bed. Start with functionality and the work that must happen together.''',
'''Classify work as essential repair, essential furnishing, comfort improvement, or optional styling. Then map dependencies. Painting precedes curtains and most wall installations; a rug decision affects sofa placement; a mattress size determines linens. Group tasks that require the same access or trade visit. Keep an owner and manager involved in any decision about whether the property can accept guests during work.

Do not treat a partially assembled room or blocked route as a finished phase. When furniture is stored on site, account for the storage footprint, packaging, and cleaning access. If listing images show amenities that are temporarily unavailable, update the listing and guest communication through the normal operating process before the stay.''',
'''Hypothetical three-phase refresh: first, replace a damaged bed and restore the bedroom’s full lighting and linen setup during a planned closure. Second, update living-room seating and test the dining route after all cartons leave. Third, add artwork and a reading corner once the core layout is confirmed. A new patio set waits until secure storage and local weather procedures are ready. The phases are based on dependencies, not a guaranteed number of days or a promised revenue effect.''',
'''Document the current condition and decide which functions must be complete before the property is offered to guests.
Draw the dependencies between painting, mounting, assembly, textile sizing, and photography.
Group work that shares a contractor, delivery visit, or room closure, including packaging removal.
Identify storage and access requirements for every phase so deliveries do not occupy guest routes.
Reinspect each completed phase and reconcile the listing, inventory, and reset instructions.''',
'''Approve a phase only after a physical walkthrough. Test the items together, not merely as individual deliveries: open doors, pull chairs out, plug in lamps, and make the bed. Record unfinished optional work separately from functional defects. If a delay affects an essential function, revise the launch plan rather than assuming guests will work around it. Keep a final photograph set that reflects the completed state.''', ['shopping'])

guide('planning', 'keep-repair-replace-audit', 'Audit Existing Furniture: Keep, Repair or Replace', 'Evaluate retained furnishings with condition records, functional tests, repair quotes, fit checks, and recall searches.',
'''A refresh does not require replacing every existing piece. An attractive table that fits the room and can be maintained may be worth keeping. Conversely, a low-cost item can become expensive when it repeatedly needs repair. Use a recorded condition audit to decide item by item rather than making the whole property “new” by default.''',
'''Give each item an identifier and examine its function, structure, finish, cleanability, and fit. Note wobble, loose hardware, damaged upholstery, missing components, and access conflicts. A cosmetic scratch and a structural crack are different problems. Stop using an item with a suspected safety defect until qualified assessment or replacement resolves it; styling cannot make that defect acceptable.

Check identifiable products against the CPSC recall database. For repairs, request a scope and cost that includes collection, materials, labor, and return delivery. Compare that with a suitable installed replacement and the effect on schedule. Retaining an item also requires updating the care record, not simply leaving it off the new purchase list.''',
'''Hypothetical audit: the dining table is stable and correctly sized, but its surface needs a finish repair that a specialist quotes at $220. A comparable installed replacement is assumed to cost $700. The manager can protect the table during the repair interval, so repair remains a candidate. One chair has a cracked frame; it is removed from service and replaced after a matching safe option is checked. The sofa stays because its frame, cushions, dimensions, and approved cleaning process all pass inspection.''',
'''Photograph each item from the front and underneath, recording model details and visible condition.
Test stability and intended function without improvising load tests that could damage the item or cause injury.
Search identifiable models for recalls and follow the manufacturer’s instructions for any affected product.
Get written repair scope and timing; compare with the full installed replacement cost.
Label the decision keep, repair, replace, or specialist assessment, with an owner and follow-up date.''',
'''Use the audit as the start of the furnishing inventory. When a retained piece dictates a finish or dimension, tell the designer before approving nearby purchases. Save receipts for repairs and record what was done. Recheck repaired functions at handover. Where the condition is uncertain, get the appropriate specialist’s view before deciding that a piece is fit for guest use.''', ['recalls','warranty'])

guide('planning', 'measurement-photo-brief', 'Create a Measurement and Photo Brief for Remote Design', 'Give a remote designer a reliable room survey with dimensions, annotated photos, fixed constraints, and delivery-route measurements.',
'''Remote design needs a shared record of the space. Wide-angle images alone can exaggerate room size and hide an outlet or door swing. A useful survey pairs a simple measured drawing with labeled photos so the designer can relate each observation to the plan and ask focused follow-up questions.''',
'''Use consistent units and identify the measuring person and date. Draw each room with wall lengths, ceiling height where relevant, door openings, windows, built-ins, vents, and outlets. Distinguish the rough room envelope from usable space; a radiator or sloped ceiling can change what fits. Measure the actual bed frame or sofa when existing furniture remains.

Photograph every wall straight on, then take corner views that show connections between walls. Label photos with room and wall letters rather than sending an unexplained camera roll. Include close-ups of constraints and a separate delivery survey: access door, stair turns, elevator, landing, and the path from vehicle to room. Verify uncertain dimensions before ordering a tightly fitted piece.''',
'''Hypothetical brief: “Bedroom B, wall C” has a 108-inch length, with a door occupying one end and a vent near the other. The retained dresser is 42 inches wide and 18 inches deep. An annotated photo shows an outlet behind it. The drawing flags an unmeasured door-clearance question for the local person to confirm. That gap remains unresolved in the brief; the designer does not treat the room’s apparent width in a photo as proof that another cabinet will fit.''',
'''Sketch rooms with wall labels and record units on every page, including any approximate or unconfirmed dimension.
Locate doors, windows, vents, outlets, fixed equipment, and existing furnishings on the same drawing.
Capture straight-on wall photos and corner views using the corresponding room and wall labels.
Measure the delivery route and note elevator booking, parking, or building access requirements to confirm.
Ask a second person to verify critical fit dimensions before nonreturnable or custom orders are approved.''',
'''Package the drawing, photos, and open questions in one organized folder. Keep revised measurements dated so the designer knows which version governs. A good brief does not need a polished CAD model; it needs clear evidence and honest uncertainty. Use a local professional for measurements or reviews that involve complex built-ins, structural changes, or regulated work rather than guessing from photos.''', ['shopping'])

guide('planning', 'guest-capacity-furnishing-matrix', 'Match Furnishings to the Guests Your Listing Can Host', 'Build a capacity matrix for sleeping, dining, lounging, luggage, and everyday supplies without confusing furniture count with permitted occupancy.',
'''A listing may offer enough beds for a group while providing too few dining chairs or places to put bags. Make a furnishing capacity matrix around the actual guest group you intend to host. The matrix helps coordinate the rooms; it does not determine legally permitted occupancy, which must be established separately.''',
'''List activities down one side and intended users across the top. Sleeping, indoor dining, lounging, luggage storage, charging, towel drying, and breakfast preparation often reveal different constraints. Count usable places under realistic conditions. A decorative chair with no table access is not an indoor dining seat, and a sofa bed in sleeping mode may consume the living room’s circulation.

Record shared resources and tradeoffs. If two guests use the sofa bed, where do they keep their bags and bedding during the day? If a patio table is part of the experience, what happens in rain or cold weather? Set the advertised guest capacity from the permitted operating plan and functional reality, not the maximum number of cushions that can fit.''',
'''Hypothetical four-guest rental: two bedrooms provide four sleeping places, the dining table has four accessible chairs, and the living room provides four comfortable seats. Each bedroom has two luggage locations and reachable charging points. The patio has only two loungers, so it is described as a small outdoor sitting area rather than a group dining space. The matrix reveals that four towel-drying positions are missing; adding appropriate hooks is more useful than another accent table.''',
'''Confirm the intended and permitted guest count through the owner’s normal operating review before planning furniture quantities.
Count usable sleeping, dining, and lounging places with convertible furniture opened and chairs pulled out.
Allocate luggage, clothes, charging, and towel-drying locations by room rather than assuming guests will share everything.
Identify weather-dependent amenities and provide an honest description of their practical limits.
Test the setup with the intended group’s activities and correct shortages before photography and listing updates.''',
'''Review the matrix whenever a layout or bed type changes. A larger bed can reduce space for luggage; another sleeper can create shortages in several rooms. Keep the matrix with the room plan and stocking list so the team does not solve capacity one product at a time. Describe the completed arrangement accurately, including any shared or convertible spaces.''', ['routes'])

guide('planning', 'furniture-cost-per-use', 'Compare Furniture Options with a Cost-per-Use Scenario', 'Use transparent repair, replacement, and turnover assumptions to compare furnishing options without forecasting rental revenue.',
'''Purchase price alone does not show how two furnishings might perform operationally. A cost-per-use scenario can help compare a repairable item with a cheaper disposable alternative. The usefulness comes from revealing assumptions, not from turning those assumptions into a promise about lifespan or return on investment.''',
'''Choose a unit that matches the decision, such as guest stays or occupied nights, and use the same unit for both options. Add purchase, delivery, installation, expected repairs, and replacements over a stated planning horizon. Divide by the assumed number of uses. Exclude unrelated operating costs unless both alternatives affect them in a documented way.

Model a second scenario in which the assumed life or repair cost is worse. If a small change reverses the result, the decision needs better product evidence. Count a replacement cushion as a repair only if it is actually available and compatible. A retailer’s durability language does not establish the number of stays an item will survive.''',
'''Hypothetical comparison over 200 guest stays: sofa A costs $1,000 installed and has an assumed $200 cushion replacement, totaling $1,200, or $6 per stay. Sofa B costs $700 installed, but one assumed full replacement adds another $700, totaling $1,400, or $7 per stay. If B lasts the whole horizon, it instead costs $3.50 per stay. This sensitivity is the point: the calculation does not prove that A is better without support for the replacement assumptions.''',
'''Use the same horizon and definition of use for all alternatives, clearly separating estimates from observed records.
Include installed costs, repair labor, replacement parts, disposal, and any repeat delivery charges that apply.
Check availability and written terms for the parts assumed to keep the item usable.
Run at least one alternative life or repair-cost scenario and note whether the preference changes.
Record nonprice considerations such as comfort, dimensions, cleaning access, and the effect of an unavailable essential item.''',
'''Save the comparison with the purchase decision. After real repairs or replacements, substitute actual costs and uses to improve the next specification. Do not attach a revenue uplift or guaranteed payback period to this worksheet; it compares furnishing costs only. If both choices are close, an operational advantage such as faster parts availability may be more meaningful than a small modeled dollar difference.''', ['warranty'])
