from content.host_guides import guide

guide('launch', 'quote-scope-comparison', 'Compare Furnishing Quotes on the Same Scope', 'Build a vendor quote comparison covering design, purchasing, freight, receiving, installation, disposal, substitutions, and handover.',
'''Two furnishing proposals can have similar totals while covering different work. Compare scope before selecting by price. A room-by-room quote matrix makes omissions visible and gives the owner a concrete basis for questions, rather than relying on the label turnkey or full service.''',
'''Start with the approved furnishing scope and create one row per deliverable. Include design revisions, purchasing, freight, receiving, storage, assembly, mounting, packaging removal, styling, photography preparation, and handover documents as relevant. Mark each proposal included, excluded, allowance, or unclear. Ask for written clarification instead of treating unclear work as included.

Match quantities and product specifications before comparing totals. Record substitutions, approval requirements, fees, payment timing, and what happens if products arrive damaged or late. Keep legal or commercial terms with the owner’s appropriate review process. The worksheet is an organizational tool, not an endorsement of a provider or a guarantee of delivery.''',
'''Hypothetical comparison: proposal A includes procurement and curbside freight but excludes receiving and assembly. Proposal B includes receiving, room placement, and bed assembly while photography is separate. Once the owner adds actual quotes for A’s missing work, the difference changes. The team then compares product fit and responsibilities rather than claiming the lower initial total proves better value.''',
'''Use the approved scope as the row list and mark each proposal included, excluded, allowance, or unclear.
Confirm quantities, exact product specifications, and any proposed substitutions before comparing totals.
Separate freight, receiving, storage, installation, mounting, disposal, and photography responsibilities.
Record approval owners, payment stages, damage handling, and relevant terms for the owner’s review.
Obtain written clarifications and compare complete scope totals using current quotes for missing work.''',
'''Save the completed matrix with the selected proposal and scope. When work changes, update both documents so the original comparison does not become misleading. At handover, verify the promised deliverables, including instructions and inventory records. Do not use a general service label to infer that a vendor will handle tasks never included in the written proposal.''', ['shopping','warranty'])

guide('launch', 'furnishing-critical-path', 'Build a Furnishing Critical Path from Real Dependencies', 'Sequence room readiness, approvals, procurement, delivery, assembly, testing, cleaning, photography, and handover using stated dependencies.',
'''A launch date needs more than a row of delivery estimates. Build a dependency plan showing which tasks must finish before others can start. The critical path is the chain that determines the earliest practical completion under the current assumptions; it changes when products, access, or scope change.''',
'''List tasks with owners, prerequisites, and current duration estimates. Room preparation precedes many installations. Approved measurements precede fitted products. Furniture placement precedes final lighting and circulation checks. Functional testing and cleaning precede representative photography. Use vendor-confirmed dates where available and mark estimates honestly.

Separate delivery from readiness. A bed delivered in cartons is not an installed sleeping place. Include receiving, damage resolution, assembly, missing parts, and waste removal. Allow a review point before the property accepts guests, with essential functions verified through the owner’s operating process. Do not promise a universal installation duration.''',
'''Hypothetical sequence: paint completion unlocks curtain installation; the measured bed approval unlocks its order; receiving and inspection unlock assembly; assembly unlocks the full bedding-fit trial. Lighting, circulation, and a complete clean then unlock photography. If the bed arrives damaged, styling can continue elsewhere but the sleeping-room readiness remains unresolved. The project record shows that dependency instead of reporting the room complete because most objects arrived.''',
'''List tasks with named owners, prerequisites, estimates, and evidence needed to mark completion.
Distinguish current confirmed vendor dates from assumptions and track changes as they occur.
Include receiving, inspection, assembly, missing-part resolution, testing, cleaning, and disposal.
Identify the current dependency chain that controls readiness and review it after delays or substitutions.
Set a documented functional-readiness review before photography and the normal guest-launch decision.''',
'''Keep the schedule visible to the buyer, installer, manager, and owner. When a delay happens, update the dependent tasks and explain the effect; simply moving one date can hide a new conflict. Preserve a final commissioning and handover interval. The plan coordinates work and uncertainty without claiming that furnishings will produce a guaranteed launch date or financial result.''', ['shopping'])

guide('launch', 'delivery-route-fit-survey', 'Survey the Delivery Route for Oversized Furniture', 'Check packaged and assembled dimensions against entrances, turns, stairs, elevators, access rules, and the vendor’s delivery method.',
'''Furniture can fit in the room but fail to reach it. Survey the full delivery route before approving oversized or nonreturnable items. The route starts where the vehicle can legally and practically unload and includes every turn, opening, stair, and access requirement before the final placement.''',
'''Obtain both packaged and assembled dimensions, weight, and the supplier’s handling requirements. Measure actual clear openings rather than nominal door sizes. Record corridor turns, stair landings, ceiling constraints, elevator dimensions, and any building booking rules. Photographs help explain the route but do not replace critical measurements.

Ask the delivery provider to confirm suitability and any disassembly or special handling. Do not assume that a diagonal measurement alone proves a rigid item can turn through several confined spaces. Some components may be removable only through a supported procedure. Use a professional survey for uncertain fit and avoid improvised lifting or alterations to the building.''',
'''Hypothetical sofa order: the living room easily accommodates the sofa, but its packaged width exceeds an interior clear opening and a stair turn remains uncertain. The vendor reviews measured drawings and photos, then confirms whether supported disassembly or another delivery method is available. The owner holds the order until the route is resolved, or chooses a sectional with confirmed component fit rather than relying on a retailer image.''',
'''Record unloading access, parking or booking requirements, and the complete vehicle-to-room route.
Measure clear openings, turns, stairs, landings, elevators, and relevant height constraints with consistent units.
Obtain exact packaged and assembled dimensions, weight, and handling instructions for the ordered version.
Ask the provider to confirm fit and supported disassembly or special handling in writing.
Resolve uncertain routes with an appropriate professional before committing to difficult-to-return furniture.''',
'''Keep the route survey with the receiving plan and send only necessary information to the delivery team through the normal process. Repeat the fit review when the model changes; similar-looking furniture can ship in a different carton. A complete survey also helps allocate people, time, and building access, so delivery readiness becomes a documented part of the project.''', ['shopping'])

guide('launch', 'receiving-damage-log', 'Prepare a Furniture Receiving and Damage Log', 'Record shipment identifiers, counts, packaging condition, product discrepancies, photographs, vendor deadlines, and follow-up owners.',
'''A delivery is not complete merely because cartons reach the property. A receiving log records what arrived, visible condition, discrepancies, and the next action under the supplier’s process. Prepare it before dispatch so the receiving person knows which information matters and who can resolve an issue.''',
'''List expected items by purchase identifier, model, finish, quantity, and carton count where known. Confirm the receiving location and responsible person. Read the vendor’s inspection, return, and damage-reporting instructions in advance; do not assume every seller uses the same deadline or process. Keep packaging or evidence according to those instructions until the issue is resolved.

Photograph the relevant condition and labels without exposing private delivery or billing details in public files. Compare contents to the order and note missing components. Do not conceal damage through installation or improvised repair while a supplier response is pending. Suspected unsafe items remain out of service until properly resolved.''',
'''Hypothetical log: three dining chairs arrive as expected, while the fourth carton contains the wrong finish. The receiving person records the order identifier, photos, carton label, and discrepancy, then contacts the assigned buyer through the project process. The buyer follows the seller’s stated reporting procedure. The room’s completion status remains open until the correct usable quantity is confirmed, rather than counting the mistaken item as installed seating.''',
'''Prepare the expected item, finish, quantity, and shipment list before dispatch and assign the receiving person.
Read the seller’s actual inspection, damage-reporting, return, and packaging instructions for the purchase.
Record received counts, labels, visible condition, missing parts, and order discrepancies with useful photographs.
Assign each issue an owner, the vendor’s stated deadline, and a follow-up action.
Verify the resolved item and update installed inventory before closing the receiving record.''',
'''Reconcile the log with invoices and final inventory during handover. Keep confidential order details in appropriate project records. If a product is returned or substituted, link the new item to the original issue so costs and delays remain understandable. This process creates evidence for the team; it does not determine legal rights or replace the vendor’s specific terms.''', ['shopping','warranty'])

guide('launch', 'substitution-approval-gates', 'Set Approval Gates for Furniture Substitutions', 'Review replacement products for fit, appearance, care, function, cost, availability, and route constraints before approving a substitution.',
'''A delayed product can create pressure to accept something similar. Similar appearance is not enough when dimensions, care, hardware, or assembly differ. Agree on substitution gates before purchasing so the buyer knows which changes can be proposed and which require a fresh design or operational review.''',
'''Define the functions and constraints the original product satisfies. A bed substitution needs frame dimensions, mattress compatibility, delivery fit, assembly, and linen coordination. A lamp needs fixture and bulb compatibility as well as style. A sofa needs open dimensions where convertible, maintenance support, and the installed footprint.

Compare total cost and timing on the same scope, including freight, receiving, and installation. Confirm actual availability rather than treating a shopping-page estimate as a guarantee. Keep the approval with product identifiers and supporting documents. A verbal “close enough” should not replace the record that the installer and manager will rely on.''',
'''Hypothetical dining-chair substitution: the alternative matches the wood color but has arms and a wider seat. Testing the plan shows it reduces practical dining capacity at the approved table. The buyer proposes another model with confirmed dimensions and care information. The owner approves only after the pullout test and full cost comparison are updated. The substitution changes the inventory and reset photographs as well as the shopping list.''',
'''Record the original product’s required function, dimensions, finish, care process, and installation constraints.
Require exact replacement identifiers and current supporting specifications rather than a similar product photograph.
Repeat affected fit, delivery, compatibility, and operational tests before approval.
Compare complete cost and timing, clearly separating confirmed information from estimates.
Save the approval and update scope, schedule, inventory, care register, and reset documentation as applicable.''',
'''If a substitution arrives without approval, hold the affected completion step and resolve it through the project owner. Do not let the final inventory describe the original product while a different one is installed. At handover, inspect actual labels and dimensions against approved decisions. Clear gates allow practical substitutions while keeping the design’s functional requirements visible.''', ['shopping','warranty'])

guide('launch', 'test-stay-commissioning-log', 'Commission the Furnished Rental with a Test-Stay Log', 'Walk arrival, sleeping, dining, work, storage, controls, and reset tasks to identify functional issues before launch.',
'''A room-by-room visual inspection can miss problems that appear only during use. A test stay walks the guest journey through the installed property and records functional issues before launch. Use a tester who does not already know the setup, with a clear scope and privacy-conscious record.''',
'''Start with arrival, luggage, and light controls, then test the supplied sleeping, dining, work, and outdoor activities. Open convertible furniture if offered. Use the actual linens and storage locations. Check whether instructions match the installed controls and amenities. The tester should report observations, not certify technical systems outside their competence.

Pair the guest journey with a cleaner’s reset trial. An arrangement can be comfortable for one evening yet difficult to restore reliably. Record each issue, its category, severity, owner, and completion evidence. Suspected safety or technical faults go to the appropriate professional and operating process. Keep access credentials and personal records out of broadly shared logs.''',
'''Hypothetical commissioning: the tester finds the patio light control unclear, two dining chairs conflict with the service route, and an extra blanket location is undocumented. The team corrects control information, revises the tested chair arrangement, and updates the clean-storage instructions. The owner rechecks each issue. A decorative artwork adjustment stays on an optional list; it does not conceal unresolved essential sleeping or circulation functions.''',
'''Define the test scope and choose someone who can observe the property without relying on prior setup knowledge.
Walk the complete arrival-to-departure activities using installed furniture, controls, textiles, and supplied items.
Run a cleaner reset trial and record handling, storage, or access conflicts alongside guest-use findings.
Assign issues to appropriate owners and escalate technical or suspected unsafe faults for qualified assessment.
Recheck completed fixes and retain clear evidence before the normal launch decision.''',
'''Use the log to produce the final guest instructions, inventory, and reset photos. A successful trial does not guarantee every guest’s experience or replace professional commissioning of technical systems. It does create a practical record of what was tested and resolved. Repeat relevant parts after major changes or recurring feedback rather than assuming the initial approval remains valid forever.''', ['routes','warranty'])

guide('launch', 'furnishing-handover-pack', 'Hand Over the Furnishing Project with a Usable Record Pack', 'Deliver scope, inventory, care instructions, warranties, spare records, reset photos, unresolved issues, and responsible contacts.',
'''A finished room is only part of the handover. The operating team needs enough information to clean, inspect, repair, and replace its contents after the original buyer or designer leaves. Assemble the handover pack during the project so important labels and decisions are not lost by launch day.''',
'''Include the approved scope, final inventory, actual product identifiers, care and assembly documents, warranties, receipts in appropriate private records, and spare-stock information. Add room-reset photos and ordinary guest-control instructions. Record approved substitutions so the documents match the installed property. Keep confidential billing, access, and account details separated from general working guides.

Close the pack with unresolved issues and responsibilities. Mark essential defects distinctly from optional styling, assign an owner, and state the evidence needed to close each item. Ask the manager and cleaner to find several documents in a trial handover. A large folder is not useful if the team cannot identify the right care instructions.''',
'''Hypothetical handover trial: the manager is asked to locate the installed sofa’s cover part, the bedroom paint specification, and the patio reopening process. Two are easy to find; the paint record still names the original selection rather than the substituted product. The designer corrects it before handover. The final checklist records what was delivered and who maintains each working document after launch.''',
'''Reconcile the approved scope, final product inventory, substitutions, and completion evidence against the installed rooms.
Provide care, assembly, warranty, spare, and replacement information linked to item identifiers.
Include reset photographs, control instructions, and seasonal procedures used by the local operating team.
Separate confidential receipts, billing details, access information, and account data into appropriate private records.
Test document retrieval with the manager and cleaner, then assign ownership of future updates and open issues.''',
'''Keep a dated version of the pack and a practical current working view. After replacements or layout changes, update the affected records rather than relying on the original project folder. The handover is complete when the team can use the information to maintain the property and clearly see what remains unresolved, not when every file has been uploaded.''', ['warranty','shopping'])
