from content.host_guides import guide

guide('layouts', 'arrival-luggage-path', 'Test the Arrival Route with Luggage Before Furnishing', 'Walk the route from the entrance to beds and luggage storage with bags, door swings, lighting, and furniture in use.',
'''Guests first experience a rental while carrying bags and finding their way through unfamiliar rooms. A furniture plan that looks generous on paper can feel awkward when the front door opens into a chair or the only luggage space is behind a bed. Test the arrival journey before approving the final layout.''',
'''Mark the entry, the first place to put a bag, and the route to each sleeping area. Draw door swings and furniture in ordinary use, not only tucked into its neatest position. Include the route to switches and any indoor steps. Keep luggage storage out of the path rather than treating the circulation area as spare floor space.

Use actual bags and a temporary furniture outline to reveal conflicts. This is a usability exercise, not an accessibility compliance assessment. If you intend to describe an accessible route or make structural changes, use the relevant requirements and qualified review. A successful walk with one suitcase does not establish that every guest or mobility device can use the route.''',
'''Hypothetical entry: a console sits directly beside the inward-opening door, and its depth leaves little room for a guest and suitcase to enter together. Moving it to another wall creates a clear first landing point. In the bedroom, a luggage rack originally blocks the wardrobe when opened; it moves to a measured location beside the dresser. The owner walks the route with the door fully open, then again with the rack unfolded and a chair pulled out.''',
'''Draw the entrance, internal doors, steps, switches, and route to every sleeping room on the furniture plan.
Test with typical luggage and with the furniture positions guests are likely to use during a stay.
Provide an obvious first bag location that does not obstruct a door, stair, or travel path.
Check that the route remains understandable after dark using the installed lighting and controls.
Record unresolved access issues and obtain appropriate professional review before making accessibility claims.''',
'''Keep the arrival route in the room-reset photographs so a cleaner does not gradually relocate a rack into the path. Recheck after adding a bench, holiday decoration, or additional sleeping furniture. If the best solution is fewer objects, remove the unnecessary piece rather than asking guests to move furniture each time they arrive. The layout should explain itself through clear placement.''', ['routes'])

guide('layouts', 'dining-chair-pullout-test', 'Plan a Dining Area with Chairs Pulled Out', 'Evaluate dining-table fit using seated positions, chair pullout, nearby doors, service routes, and a full-capacity trial.',
'''A dining set can fit inside a room while failing in use. Chairs need space to pull out, guests need to reach their seats, and somebody may need to pass while others remain seated. Test those activities together before approving the table footprint or advertising the dining capacity.''',
'''Draw the table and the chosen chairs using actual dimensions. Mark a realistic occupied position and a pulled-out position rather than relying on a generic rectangle around the table. Check conflicts with walls, doors, kitchen cabinets, and adjoining seating. A bench may change the footprint but can require guests to slide past each other; evaluate that tradeoff explicitly.

Use tape, sample chairs, or temporary objects to create a physical trial. Do not present a chosen design allowance as a universal code clearance. Where accessibility or building requirements apply, verify those requirements separately. Include cleaning access: a tight table that cannot be moved or reached underneath can add time to every reset.''',
'''Hypothetical six-seat dining plan: four chairs work comfortably, but the two end seats conflict with a kitchen route and an opening cabinet. The room does not support the proposed six-seat arrangement as drawn. The designer tests a different table orientation and slimmer chairs, then decides whether the property should instead describe a four-seat indoor dining area. Outdoor chairs are not counted as indoor dining seats when weather makes them unavailable.''',
'''Measure the actual table, legs, chairs, and any bench rather than using only the advertised tabletop size.
Test every seat with chairs occupied and pulled out, including the end positions and bench access.
Open nearby doors and cabinet fronts while another person walks the ordinary service route.
Have the cleaner try the under-table access and movement needed for a full room reset.
Document the usable seating count and obtain specialist review for any applicable accessibility or building requirement.''',
'''Photograph the confirmed arrangement from useful angles and keep the plan with the inventory. If substitute chairs are wider or have arms, repeat the trial before accepting them. A small dimensional change can remove a usable seat even when the table is unchanged. At listing review, show the actual dining arrangement so guests can understand how their group will use it.''', ['routes'])

guide('layouts', 'sofa-bed-open-layout', 'Draw the Sofa Bed Open Before You Buy It', 'Plan convertible seating in sleeping mode with circulation, luggage, bedding storage, privacy, and morning reset requirements.',
'''A sofa bed is two layouts in one. Its daytime footprint does not show the space needed when the mechanism is open and bedding is in use. Plan both arrangements before adding the sleeping places to a rental’s furnishing matrix. The open layout often reveals costs beyond the sofa itself.''',
'''Obtain the manufacturer’s full open dimensions and operating instructions. Add space to reach the mechanism, approach the sleeping surface, use storage, and follow the room’s normal route. Show where movable tables go; they should have a defined location that does not block another room. Test the setup physically if possible rather than estimating extension from a photograph.

Coordinate bedding, luggage, charging, reading light, and privacy. Guests using the living room as a bedroom may need a different arrangement for evening activities than guests in private rooms. Make the convertible nature of the space clear in the listing. Furniture quantity does not establish permitted occupancy; verify the operating limit separately.''',
'''Hypothetical small living room: the sofa bed opens across the route to the kitchen, and the coffee table has nowhere safe to go. Removing the table alone does not solve the blocked route. A different orientation is tested, but it leaves no useful luggage location. The owner chooses ordinary seating and retains the existing guest capacity instead of describing an uncomfortable conversion as an extra bedroom.''',
'''Collect full open dimensions, mechanism clearance, mattress specification, and the product operating instructions before ordering.
Draw daytime and nighttime plans with all movable furniture shown in its actual alternate location.
Allocate clean bedding storage, luggage space, charging, light controls, and a realistic privacy arrangement.
Have the local team perform the complete conversion and morning reset, including linen handling.
Confirm the listing accurately describes the shared convertible space and the separately verified guest capacity.''',
'''Store illustrated operating instructions where guests can find them and train the reset team on the mechanism. Do not leave the solution dependent on guests lifting heavy furniture without a plan. If the sleeping function is removed or changed, update the inventory and listing through the normal operating process. Recheck the layout after any substitute sofa, mattress, or nearby table is installed.''', ['shopping','routes'])

guide('layouts', 'work-dining-conflict-plan', 'Separate Work and Dining in a Compact Rental', 'Plan a laptop workspace with reachable power, a suitable chair, lighting, storage, and clear limits when dining space is shared.',
'''A laptop in a listing photo does not make a space usable for work. The guest needs a suitable surface, seating, reachable power, light, and somewhere to move work items when the room changes function. In a compact rental, decide honestly whether work and dining can happen at the same time.''',
'''Map the activities before choosing a desk. If the dining table is the workspace, test the actual chair and the route to power without trailing a cable across circulation. Check glare on a screen during daylight and the task light after dark. Preserve a place to eat without placing plates on work equipment. A separate desk may be preferable only if it does not compromise a more essential route or storage function.

Include small practical details: a clean surface, cable reach, and a clear explanation of what is provided. Describe the space accurately rather than suggesting a private office where the workstation sits in the living room. Network performance is an operational specification that should be tested separately; furniture planning cannot guarantee connectivity.''',
'''Hypothetical studio: a deep console is proposed as a desk, but its decorative stool is awkward for sustained use and the outlet is across the entrance path. The revised arrangement uses a suitable chair at one end of the dining table, with power positioned by an appropriate installer where needed. A nearby shelf holds laptop items during meals. The listing describes a shared table workspace and shows its location rather than implying a separate office.''',
'''Identify whether work and dining must happen simultaneously for the guest group the property intends to host.
Test the surface, chair, legroom, and ordinary laptop arrangement with actual furniture samples where possible.
Locate reachable power without temporary cables crossing doors, paths, or places likely to get wet.
Check daylight glare and nighttime task lighting from the seated position.
Provide a storage or reset location for work items and describe the shared or private nature of the space accurately.''',
'''Ask the trial-stay tester to use the workstation through a meal and note the transitions. Record furniture and lamp positions in the reset guide so the setup remains usable. If power changes require electrical work, use the appropriate professional. Review actual guest feedback about the space before adding more equipment; a larger desk is not always the answer to a conflict between activities.''', ['bulbs','routes'])

guide('layouts', 'bedside-function-footprint', 'Plan a Bedside Area Around Reach and Storage', 'Coordinate bedside furniture, reading lights, charging, curtains, doors, and luggage without crowding the bedroom.',
'''A bedroom can look symmetrical while leaving one guest unable to reach a light or set down a phone. Plan the bedside area around use from the installed bed, not just matching nightstands in a photograph. The mattress, frame, lamp, outlet, and curtain all affect the usable footprint.''',
'''Draw the actual bed-frame dimensions, including any protruding headboard or feet. Check bedside surfaces from a sitting and lying position. If the space is limited, a smaller surface or appropriately installed wall solution may serve the activity better than a deep cabinet. Do not let a nightstand block a drawer, wardrobe, curtain operation, or ordinary path.

Plan light controls and charging reach for both sides where the layout supports them. Confirm electrical work or wall mounting with appropriate installers. Avoid exposed cords across routes and do not place charging equipment where it conflicts with wet items. Check access for making the bed; a tightly wedged frame can make the cleaner’s job unnecessarily difficult.''',
'''Hypothetical bedroom: a wide frame and two 24-inch cabinets fill the wall visually, but one cabinet overlaps the door swing. Testing with smaller tables restores the door’s operation and leaves room to change linens. One lamp’s switch is behind the headboard, so the team chooses a fixture with a reachable control. The final photograph is slightly less symmetrical but more useful for the two people actually sleeping there.''',
'''Measure the complete frame and installed mattress height before choosing the bedside surfaces and light positions.
Test reach from both sides of the bed for the lamp control, phone surface, and charging connection.
Open doors, drawers, curtains, and wardrobes with the bedside furniture in its final location.
Check that linens can be changed and the floor cleaned without unsafe or excessive furniture movement.
Document suitable cord routes and confirm required mounting or electrical work with the responsible installer.''',
'''Keep the final positions in a bedroom reset photo, including which control operates each light. If a mattress height or bed frame changes, repeat the reach test. Do not assume the old arrangement still works. A bedside plan is complete when the essential activities work together and the team can maintain them, not when every surface has a decorative object.''', ['anchor','bulbs'])

guide('layouts', 'family-storage-zones', 'Create Family Storage Zones Without Filling the Room', 'Allocate luggage, clothes, shoes, toys, and supplied amenities by activity while keeping travel paths and furniture stability in view.',
'''Families bring several kinds of belongings, and they do not all belong in the same basket. A room can accumulate clutter even when it has plenty of decorative storage. Plan zones around arrival, daily dressing, play, and packing so guests can understand where items go without rearranging the furniture.''',
'''Separate luggage from clothes, shoes from bedding, and supplied amenities from guest belongings. Keep the most frequently used storage visible and reachable for its intended users. Use furniture suited to the load and installation conditions. CPSC’s Anchor It guidance provides background on furniture tip-over prevention; follow the exact product and installation instructions rather than assuming a low cabinet needs no assessment.

Choose containers that can be cleaned and checked during a reset. A deep toy chest may be less practical than a simpler arrangement depending on the product and users; review product safety and recalls when providing items for children. Avoid describing the property as childproof based on furniture choices. The furnishing plan supports use but cannot eliminate every hazard.''',
'''Hypothetical two-bedroom family rental: suitcases have a location in each sleeping room, shoes have a washable tray near the entry, and a small set of provided games occupies a labeled shelf. An oversized decorative trunk is removed because it consumes the play area and is difficult for the cleaner to inspect. The plan leaves empty storage for guests rather than filling every shelf with host décor.''',
'''Identify which belongings guests bring for the activities the property supports and allocate separate storage zones.
Leave genuine empty space for guest possessions instead of using every cabinet as decorative display or owner storage.
Check product suitability, stability, mounting requirements, and recalls for provided furniture or children’s items.
Test the room with luggage stored and games in use while keeping doors and travel paths clear.
Ask the cleaner to empty, inspect, and reset the storage so missing items and cleaning needs are visible.''',
'''Photograph the intended zones and label only where a label helps guests use them. Keep owner-only supplies clearly separate. Reevaluate the plan if storage regularly overflows in trial stays or feedback; adding another box can conceal a layout problem. Remove damaged supplied items promptly through the operating process and replace them with products reviewed for the intended use.''', ['anchor','recalls'])

guide('layouts', 'entry-wet-dry-zones', 'Separate Wet Gear from Dry Storage at the Entry', 'Plan shoes, coats, umbrellas, beach gear, or ski equipment around drying, cleaning, storage, and a clear entrance route.',
'''The entry is where outdoor weather becomes an indoor maintenance issue. Wet shoes and gear need a place that can be cleaned and dried without soaking luggage, linens, or vulnerable furniture. Design the landing area around the actual activities your property supports and the team’s ability to reset it.''',
'''Map the first place guests can put wet items, a location for dry bags, and the route into the house. Check that mats, trays, hooks, or racks fit with the door fully open. Use products suited to the expected load and moisture exposure, with appropriate installation. Avoid putting absorbent storage baskets directly where wet gear drains.

Plan drying and ventilation as well as containment. A tray can collect water but does not remove it. Keep routine cleaning access and inspection in the reset process. Persistent dampness or mold concerns need an appropriate moisture response; the EPA moisture guide is useful background, but the layout itself is not a remediation plan.''',
'''Hypothetical outdoor-oriented rental: guests previously placed wet boots beside a wooden console and jackets on dining chairs. The revised entry provides a suitable boot tray and coat hooks with verified fixing, while luggage goes on a separate dry surface. The team tests the door with the tray occupied. A reset instruction assigns tray emptying and drying to the cleaner instead of letting collected water remain between stays.''',
'''List the weather-exposed items likely to arrive and distinguish their wet storage from clean dry belongings.
Choose trays, mats, and hooks for the actual exposure and load, following product installation and care instructions.
Open the entrance fully and walk the route with the storage in ordinary use.
Provide a practical drying or handling process rather than relying on a container to solve moisture.
Include emptying, cleaning, drying, and condition inspection in the entry reset record.''',
'''Observe the arrangement during a trial stay in representative weather if possible. If guests still leave wet gear elsewhere, examine reach, signage, capacity, and drying practicality before adding décor. Keep supplied equipment and owner storage out of the entrance route. Update the seasonal plan when the guest activity changes so a summer beach setup does not automatically become a winter gear-storage plan.''', ['moisture','routes'])

guide('layouts', 'cleaner-access-layout-review', 'Review a Furniture Plan from the Cleaner’s View', 'Test access under beds, around rugs, behind furniture, and through the linen route before a rental layout is approved.',
'''The cleaner uses a room differently from the photographer. They need to change linens, reach dust, move equipment, and inspect for lost items or damage. Review those activities before approving furniture placements so the design can remain in good condition without relying on awkward improvisation every stay.''',
'''Ask the actual cleaning team to walk the plan with their normal equipment. Check access under beds, behind bedside tables, around rug edges, and inside provided storage. Identify which furnishings must move and how they can be moved according to product instructions. Do not assume a heavy bed or sofa can be shifted casually by one person.

Trace the clean-linen route and the handling of used textiles. Keep clean stock separated from wet or soiled items. Record approved cleaning products by surface rather than giving the team one universal cleaner. If a furniture position conceals a vent, outlet, or recurring damp spot, revise it or obtain appropriate review; an attractive layout should not make those features inaccessible.''',
'''Hypothetical bedroom review: a deep upholstered frame nearly touches both walls, making corners difficult to inspect and linens awkward to tuck. A smaller frame footprint and repositioned tables improve access. In the living room, a rug sits under several heavy pieces, so the proposed washing routine requires a separate removal plan. The designer records these dependencies before orders are placed instead of discovering them during the first rushed turnover.''',
'''Walk each room with the local cleaning team and the equipment they actually expect to use.
Test bed making, floor access, storage inspection, and the removal of washable textiles in their installed positions.
List furniture movement that needs extra people, equipment, or a scheduled maintenance visit rather than an ordinary reset.
Provide surface-specific care instructions and locations for clean linens, used textiles, and cleaning supplies.
Photograph the approved placement and review any inaccessible vents, controls, or moisture-prone locations.''',
'''Carry the observations into the scope, inventory, and reset guide. If a substitution changes furniture weight, base height, or textile removal, repeat the relevant part of the review. Track actual difficulties during the first resets and adjust the plan with the team. Efficient maintenance depends on access and a workable process, not simply choosing fewer decorative objects.''', ['cleaning','moisture'])
