from content.host_guides import guide

guide('lighting', 'rental-bulb-schedule', 'Create a Bulb Schedule That Survives Replacements', 'Record bulb base, shape, lumens, appearance, dimming, fixture compatibility, and spare locations for consistent rental lighting.',
'''A room can start with coordinated lighting and gradually become a mix of unrelated bulbs as replacements occur. A bulb schedule prevents the maintenance team from guessing. It records the actual specification of each installed light and makes the spare stock manageable.''',
'''Assign each fixture a location code. Record bulb base, shape, size, brightness in lumens, light appearance, and any dimming requirement. FTC’s Lighting Facts guidance explains why wattage and brightness are different measures. Check fixture limits and suitability for enclosed, damp, or other relevant conditions using the actual fixture and bulb instructions.

Group fixtures that can share the same approved bulb, but do not standardize away important requirements. A bedside lamp and a covered ceiling fixture may need different products. Integrated fixtures need their own maintenance record because they may not accept a replaceable bulb. Test the chosen bulbs with existing dimmers before ordering a large batch.''',
'''Hypothetical schedule: living-room lamps L1 and L2 use the same approved base, shape, and light appearance. The kitchen fixture K1 has a different enclosure requirement, so its bulb has a separate stock code. The cleaner reports a failed lamp and the manager selects the labeled L1/L2 spare. They do not use a brighter kitchen spare merely because the base fits. A photograph of the box and fixture record supports future reordering.''',
'''Give every fixture a room and position identifier matching the floor plan or inventory photographs.
Record the complete bulb specification and the fixture’s limits or location requirements from manufacturer instructions.
Test ordinary switching and dimming with the chosen bulb before standardizing it across the room.
Label approved spares by compatible fixture groups and store them where the responsible team can find them.
Record integrated fixtures, driver information where applicable, and the service contact separately from replaceable bulbs.''',
'''Update the schedule when a fixture or approved bulb changes. After replacement, check appearance from several positions and ensure controls still work normally. A product with the same base can differ in output, size, and compatibility. Keep the schedule simple enough that a person arriving for one maintenance visit can use it without opening several unrelated shopping lists.''', ['bulbs'])

guide('lighting', 'layered-room-lighting-test', 'Test Room Lighting by Activity, Not Fixture Count', 'Evaluate arrival, reading, dining, relaxing, and cleaning light separately using the installed furniture and actual nighttime conditions.',
'''Adding more fixtures does not automatically make a room easier to use. A bright ceiling light may still leave a reading chair in shadow or create glare on a television. Build the lighting plan around activities, then test the room with furniture in place after dark.''',
'''List the tasks each room supports. Arrival needs clear orientation; reading needs useful light at the seat; dining needs visibility at the table; relaxation may need a gentler option; cleaning needs access to a practical full-light setting. Show controls on the room plan and identify which guest activity each fixture serves.

Choose bulbs from actual specifications, including brightness and appearance, rather than treating a wattage label as a room-lighting formula. There is no universal fixture count that suits every ceiling height, surface color, shade, or occupant. Check the lighting from seated and standing positions. Use an appropriate professional for electrical work or specialized lighting requirements.''',
'''Hypothetical living room: one ceiling fixture gives adequate general visibility but reflects in the television. A lamp beside the reading chair serves reading without requiring the ceiling light. Another source gives a comfortable evening option. The team checks all combinations from the sofa, dining position, and entrance. The result is an activity plan with understandable controls, not a promise that a fixed lumen total will suit every guest.''',
'''Write the room’s activities and identify which need separate light sources or controllable combinations.
Test the actual lamps, shades, bulbs, furniture positions, and surface colors after dark.
Check glare on screens and reflective surfaces from the places guests sit and stand.
Confirm that a new guest can find the relevant switch without reaching behind heavy furniture.
Record the approved settings and provide a practical cleaning-light arrangement for the reset team.''',
'''Keep the final light positions in the reset photos and the bulb schedule. Repeat the nighttime test after changing shade opacity, wall color, or furniture placement. Those changes can alter how the same fixture feels. If a guest reports that one task is poorly lit, investigate that task directly rather than making the entire room brighter by default.''', ['bulbs'])

guide('lighting', 'dimmer-compatibility-trial', 'Trial Dimmers and Bulbs Before a Whole-Property Order', 'Check the exact dimmer and bulb combination for operation, low-level behavior, guest controls, and service documentation.',
'''A bulb labeled dimmable can still behave poorly with a particular control. Before buying the same combination for every room, test one complete installation with the actual dimmer, fixture, bulb, and wiring conditions reviewed by the responsible professional. A small trial can expose incompatibility before it becomes a property-wide maintenance issue.''',
'''Collect model identifiers and the manufacturer’s compatibility guidance. Ask the electrician to confirm the proposed combination and any limits on connected fixtures. Test switching, adjustment across the usable range, restart behavior, and any hum or flicker observed during ordinary use. Do not change wiring, load, or control settings beyond what the product instructions and professional review allow.

Evaluate the control as a guest interface too. A setting hidden behind a faceplate may be appropriate for commissioning but should not be needed for everyday use. Record the approved configuration and make the normal guest control understandable. Keep a useful full-light setting for cleaning without requiring the team to troubleshoot each room.''',
'''Hypothetical trial: the proposed bedroom bulbs illuminate normally at high output but flicker at the lowest control position. The electrician reviews the compatibility guidance and tests an approved alternative. The owner waits for that result before buying the remaining batch. The maintenance record then identifies the exact approved models, rather than saying “any dimmable LED,” so later replacements do not reintroduce the problem.''',
'''Record fixture, bulb, and dimmer model numbers and obtain their relevant installation and compatibility documents.
Have the responsible electrician review the combination and perform required installation or commissioning work.
Test normal on/off operation, adjustment, restart, and observed low-level behavior before ordering a large quantity.
Check that everyday controls are clear for guests and useful for the cleaning team.
Save the approved models and configuration, with a process for reviewing any substitute component.''',
'''If hum, flicker, heat, or unreliable operation appears later, report it through maintenance and obtain appropriate assessment. Do not treat a guest instruction as a repair for an electrical problem. Recheck compatibility when either the bulbs or control changes, even if the replacement looks identical. The trial is specific to the installed system and does not certify every product with the same marketing label.''', ['bulbs','warranty'])

guide('lighting', 'bedroom-darkness-audit', 'Audit Bedroom Light Gaps Before Ordering Curtains', 'Measure and test bedroom light entry from windows, doors, exterior lights, and devices before selecting window treatments.',
'''Blackout fabric addresses light through the material, but bedroom darkness also depends on gaps, hardware, doors, and nearby lights. Audit the room during the relevant daylight and nighttime conditions before selecting the treatment. The result should guide measurement and installation rather than relying on a product label alone.''',
'''Record where light enters: top and side gaps, a door opening, neighboring exterior lighting, or a device indicator. Photograph the room from the bed with normal lights off. Measure the window, surrounding wall, hardware position, and any vent or door conflict. Ask the installer to define suitable coverage and fixing for the actual window conditions.

Consider operation and care as well as darkness. Guests need to open the treatment easily, and the cleaner needs a supported maintenance process. CPSC guidance highlights the risks of window-covering cords; use appropriate products and installation. Do not tape over safety indicators, block vents, or obstruct exits to darken a room. Address each light source with a suitable solution.''',
'''Hypothetical bedroom: a dense curtain leaves a bright side gap because the rod ends almost at the glass edge. A wider suitable installation is assessed, while the nearby wardrobe door limits the available side coverage. A separate exterior light shines toward the window; its placement is reviewed as part of the outdoor lighting plan. The final test happens from the bed rather than from a flattering listing-photo angle.''',
'''Observe the room in daylight and at night, recording each significant source of unwanted light from the sleeping position.
Measure window and wall conditions, hardware location, and conflicts with doors, vents, or existing furniture.
Confirm product suitability, cord safety, mounting, and care instructions before approving the treatment.
Test operation and cleaning access after installation without blocking ventilation or required routes.
Describe the installed arrangement accurately instead of promising complete darkness under every external condition.''',
'''Include curtain positions and operation in the bedroom reset guide. Recheck after moving exterior lights or replacing devices with visible indicators. If a treatment catches, sags, or detaches, resolve the installation issue before asking guests to handle it differently. A darkness audit can improve comfort, but it is not a medical claim or a guarantee that every guest will sleep well.''', ['cords','darksky'])

guide('lighting', 'screen-and-mirror-glare-review', 'Review Glare from Screens, Mirrors and Glossy Surfaces', 'Test light reflections at actual guest eye positions before fixing television, mirror, lamp, and dining-table placement.',
'''A bright reflection may be almost invisible in a staged photo but distracting from a sofa or bed. Review glare at the positions guests actually use. Screen placement, shade design, window coverage, and reflective finishes interact, so the solution may involve moving one element instead of increasing or decreasing every light.''',
'''Sit at each main position and look at the television, mirror, tabletop, and other glossy surfaces. Repeat during daylight and after dark. Turn light sources on individually so the team can identify the cause. Note whether the reflection prevents a task, is merely visible, or depends on a temporary arrangement.

Try practical alternatives with temporary placements before committing to wall mounting or custom wiring. A lamp moved slightly out of a sight line may solve the issue; a very opaque shade can create a new task-light problem. Use suitable mounting and electrical work through the responsible installer. Do not solve reflections by making an ordinary route too dark.''',
'''Hypothetical living room: two lamps reflect prominently in the television from the center sofa seat. One is repositioned to support reading from a nearby chair, and the other gets a suitable shade reviewed with the fixture. Daylight glare still appears at a particular hour, so the window treatment is tested. The owner records the useful control combination for television viewing while retaining the brighter arrangement for arrival and cleaning.''',
'''Inspect screens, mirrors, and glossy surfaces from actual seated and standing guest positions.
Repeat the observation in representative daylight and nighttime conditions with light sources switched on separately.
Trial fixture position, shade, furniture orientation, and window coverage before permanent installation.
Confirm that changes preserve useful task lighting and clear routes rather than simply reducing all light.
Record approved positions and control combinations in the room reset instructions.''',
'''Revisit glare when artwork, mirrors, screens, shades, or finishes change. A replacement table with a glossier surface can alter the same room’s lighting. Ask trial-stay testers about the task they attempted rather than whether the room looked stylish. The aim is usable visibility in the installed conditions, and the test should keep that activity at the center.''', ['bulbs'])

guide('lighting', 'nighttime-switch-route', 'Make the Nighttime Switch Route Easy to Understand', 'Walk arrival and overnight routes to test switch location, labels, reachable controls, and light spill into sleeping spaces.',
'''A new guest should be able to enter a room, find useful light, and return to bed without exploring every wall. Trace the nighttime routes and controls before adding sophisticated lighting features. Familiar, well-positioned controls can be more useful than a system that needs a tutorial.''',
'''Start at the entrance after dark, then walk to bedrooms and bathrooms. Note which switches are found naturally and which appear to do nothing. Check controls with furniture in place, including curtains and open doors. Verify what each switch operates and resolve wiring or fixture issues with the responsible professional.

Use labels only where they answer a real question. A concise label such as “patio” may clarify an otherwise ambiguous control; a wall full of instructions can signal that the layout needs simplification. If suitable orientation lighting is provided, check that it does not spill directly into sleeping positions or require cords across the route. It must complement, not replace, required lighting or safety systems.''',
'''Hypothetical overnight test: the bedroom’s only light switch is beside the door, while the bedside lamp control is hidden behind the table. Repositioning the lamp makes it reachable from bed. A hallway switch has no clear function; the installer identifies and corrects the issue. The team checks that the bathroom route can be followed without using a bright ceiling light in an occupied bedroom.''',
'''Walk the arrival and overnight routes after dark without relying on prior knowledge of the switches.
Verify each control’s actual function and report nonworking or ambiguous installations to the responsible professional.
Check reach from bed, normal furniture positions, and open-door conditions.
Use brief labels only where they clarify an otherwise confusing control.
Test any orientation lighting for useful visibility, glare, cord placement, and spill into sleeping areas.''',
'''Include the control map in the handover record and keep normal guest instructions short. Repeat the test after rearranging furniture or adding automation. A disconnected lamp, changed smart-device setting, or moved bedside table can make yesterday’s instruction incorrect. Prefer a robust ordinary control path so a guest can still use the room when an optional feature is unavailable.''', ['bulbs'])

guide('lighting', 'outdoor-light-spill-audit', 'Audit Outdoor Lighting for Arrival and Light Spill', 'Plan outdoor fixtures around useful arrival visibility, shielding, controls, bedroom spill, and neighboring properties.',
'''Outdoor lighting should help guests find and use the property without illuminating every surrounding surface. Test the arrival route, seating areas, bedroom windows, and property edges after dark. An outdoor-light audit connects fixture placement with the guest experience and the local setting.''',
'''Identify the purpose of each source before selecting the fixture. DarkSky’s principles support useful, directed, appropriately limited, controlled, and warm-colored outdoor lighting. Apply that background to the specific site while verifying applicable local requirements and product suitability. Have electrical work performed by the responsible professional.

Observe spill toward windows and neighboring areas from several positions. Check shielding, aim, control behavior, and the route when motion or timer controls change state. More brightness can increase glare without helping a guest see an obstacle. Consider weather exposure and maintenance access when approving fixtures; outdoor appearance alone does not establish suitable electrical or environmental protection.''',
'''Hypothetical patio: a floodlight aimed across the seating area also shines into a bedroom window. A reviewed layout directs suitable fixtures toward the useful walking and sitting areas, with controls tested during a normal arrival. The team walks from parking to the entrance and views the property from the boundary. The chosen arrangement avoids treating a bright photograph as evidence that the lighting works well in person.''',
'''State the purpose and intended coverage of each outdoor fixture on the site plan.
Confirm location suitability, installation, and any relevant local lighting requirements with the responsible professionals.
Walk the arrival route and inspect glare and spill from seating, sleeping, and boundary positions.
Test timers or motion controls during realistic arrival and ordinary nighttime use.
Record fixture models, aiming, controls, and the maintenance access needed to keep the plan working.''',
'''Recheck the audit after landscape changes, fixture replacement, or a new bedroom treatment. If a guest reports unwanted spill, identify the source instead of assuming heavier curtains are the only solution. Keep the approved configuration in the outdoor reset plan. The audit documents observed usability and site conditions; it does not guarantee that a particular fixture meets every local rule.''', ['darksky','bulbs'])
