from content.host_guides import guide

guide('maintenance', 'furniture-product-care-register', 'Build a Product and Care Register for Each Room', 'Record furniture identifiers, approved cleaners, care documents, warranties, spare parts, and responsible contacts in one room register.',
'''A maintenance person should not have to reconstruct a furnishing purchase from an old shopping cart. Build a product and care register while the order information is available. It connects the item in the room to its model, instructions, approved care process, and replacement support.''',
'''Assign an item identifier that appears on the room plan and inventory photo. Record manufacturer, model, version, finish, dimensions, purchase date, and supplier. Save care and assembly documents as well as the warranty and receipt. Photograph labels and serial numbers where present; do not publish private order or account details in a public-facing library.

Add the approved cleaning products and method for the exact surface, including any requirement for specialist care. A general household-cleaner name is not a sufficient material schedule. EPA’s Safer Choice resources can inform product consideration, but a label does not establish compatibility with every furnishing. Confirm the actual manufacturer’s instructions and the local team’s process.''',
'''Hypothetical register line: “LR-S1” identifies the living-room sofa. The record has its model, fabric color, cover instructions, cushion part identifiers, purchase receipt, and service contact. A linked room photo shows the item. When a cover is damaged, the manager can identify the correct part and approved cleaning process without sending several messages to the original buyer. Confidential billing details remain in the owner’s appropriate private records.''',
'''Give each item a room-based identifier and use it consistently in photos, room plans, and issue logs.
Record exact product, finish, version, dimensions, purchase information, and supplier details for the installed item.
Save relevant assembly, care, warranty, and receipt documents with access appropriate to the operating team.
List approved cleaning products and methods by surface after confirming product compatibility.
Add available spare parts and a responsible contact so a future repair has an obvious starting point.''',
'''Keep the register current when substitutions, repairs, or replacements occur. At handover, ask a team member who did not buy the item to find its care document and replacement identifier. That test reveals missing information better than counting files. Keep a practical working view for cleaners while storing private financial or account records through the owner’s usual secure process.''', ['warranty','cleaning'])

guide('maintenance', 'turnover-time-motion-log', 'Use a Turnover Time-and-Motion Log to Improve the Layout', 'Observe a room reset to find extra walking, repeated handling, inaccessible cleaning points, and practical furnishing improvements.',
'''A room can be called easy to clean without anybody observing a full reset. A time-and-motion log records what the local team actually does. Use it to identify avoidable handling and layout problems, not to impose an unsupported cleaning-time target or evaluate staff from an isolated measurement.''',
'''Agree on the reset scope and observe a representative process with the cleaner’s cooperation. Record task, start and finish, extra trips, repeated handling, and the reason for interruptions. Separate routine work from unusual damage or missing supplies. The same room can take different time depending on condition, so one observation is a prompt for investigation rather than a universal standard.

Look for design changes that remove steps: reachable supplies, simpler bedding handling, fewer unnecessary decorative objects, or better furniture access. Ask the team which changes would help and check that they still support guest use. Preserve the quality of cleaning and inspection; a shorter process is not successful if it skips necessary work.''',
'''Hypothetical log: the cleaner returns to another floor three times because replacement pillowcases are stored there. A room-level clean-stock location reduces those trips. A rug requires moving several objects before vacuuming, so the owner trials a simpler decorative arrangement. The team compares another ordinary reset after the changes. Any observed time difference is recorded as this trial’s result, not advertised as an industry-wide percentage improvement.''',
'''Agree on the complete reset scope and obtain the team’s cooperation before observing tasks or recording timings.
Record ordinary tasks, interruptions, extra trips, and repeated handling with enough context to explain them.
Separate unusual condition or damage from the routine furnishing and cleaning process.
Trial a practical change proposed with the cleaner and confirm that quality and guest functions remain intact.
Compare representative observations and save the decisions, without turning one timing into a universal productivity claim.''',
'''Carry useful changes into the room-reset photographs, stock locations, and care register. Revisit the log after major furnishing changes or repeated operational complaints. If a task is slow because the product requires specialist care, acknowledge that specification rather than expecting the cleaner to bypass instructions. The log is a collaborative process tool and should remain tied to the actual room and conditions.''', ['cleaning'])

guide('maintenance', 'laundry-turnover-capacity', 'Plan Laundry Capacity Against the Turnover Schedule', 'Compare required linen loads, approved washing and drying processes, machine capacity, staffing, and off-site backup for a rental.',
'''Enough linen sets do not guarantee that the laundry process can handle a busy changeover. Compare the actual wash, dry, sort, and storage cycle with the volume the property generates. The worksheet should reveal constraints before the team is forced to return damp or incomplete stock to service.''',
'''List the textiles in one ordinary reset and group them according to their care instructions. Check usable machine capacity from the equipment and textile guidance, not only the drum’s advertised size. Include sorting, loading, transfer, drying, inspection, folding, and return to clean storage. A wash program’s duration is not the whole process.

Map the available staff time and equipment occupancy. If loads overlap across several properties, assign their capacity rather than assuming each can use the same machine simultaneously. Build a supported backup for peak volume or equipment failure. Keep used and clean textiles separated, and do not count items as available until they are properly processed and ready.''',
'''Hypothetical capacity exercise: a reset creates four compatible loads after following textile and machine instructions. Each load’s assumed wash-and-dry process occupies the equipment for two hours, totaling eight hours if processed sequentially. Sorting and handling add further work. The available on-site interval is shorter, so the owner arranges suitable off-site processing or changes the stock-and-return plan. These assumed times demonstrate the calculation; the real schedule needs measured cycles.''',
'''Count the reset textiles and separate loads by the actual washing and drying instructions.
Confirm permitted load capacity and program requirements for the equipment and textiles being used.
Measure the full process, including handling, inspection, folding, transport, and clean storage.
Map equipment and staffing availability across the actual properties and turnover pattern.
Define an off-site or spare-stock contingency that keeps unsuitable or damp textiles out of guest use.''',
'''Review the worksheet after a busy period, changed linen specification, or machine replacement. A larger machine may not solve drying or handling bottlenecks. Update par stock together with the processing plan so the two assumptions remain consistent. Record actual failures and delayed returns to improve the next planning cycle rather than relying on an ideal schedule that never occurs.''', ['moisture','shopping'])

guide('maintenance', 'spare-parts-minimum-stock', 'Set Minimum Stock for Small Furnishing Parts', 'Choose useful spares from failure impact, reorder lead time, model compatibility, storage space, and actual maintenance history.',
'''A drawer pull, compatible lamp bulb, or specific cushion cover can matter more during a reset than a spare decorative object. Build small-parts stock around what can interrupt the property and what the team can replace using approved procedures. Avoid buying a broad assortment that nobody can identify later.''',
'''List serviceable parts in the product register, then consider failure impact, current lead time, observed frequency, and storage requirements. Confirm the exact identifier and version before ordering. A visually similar fastener or electrical component is not necessarily a suitable substitute. Specialist work should remain with the appropriate professional even when the replacement part is on site.

Set a minimum and reorder point for each approved spare, distinguishing essential stock from optional convenience. Keep receipts and current availability notes. Do not assume a supplier will continue stocking a part indefinitely. Label storage so a person attending one maintenance visit can find the correct item without opening every box.''',
'''Hypothetical stock plan: approved bulbs shared by several lamps have a small labeled reserve. One model-specific cushion cover has a separate location because it is slow to reorder. Decorative knobs that are easy to obtain locally are recorded but not all held as spares. The owner does not stock random screws for structural repairs; the register identifies the product’s approved parts and the appropriate installer or service provider.''',
'''Start with the serviceable parts listed for installed products rather than an unrestricted hardware shopping list.
Record model compatibility, current availability, reorder process, and the operational impact of a missing part.
Set minimum stock and reorder points using explicit assumptions or actual failure records.
Store and label parts according to product guidance, separating incompatible versions and private records.
Identify which replacements the local team can perform and which require a qualified service provider.''',
'''After every use, record the part fitted and update the count. Review unused stock when furniture changes so obsolete spares do not masquerade as available replacements. Adjust reorder points from actual delays and failures. A useful spare system is small, accurate, and connected to the installed inventory; volume alone does not make it reliable.''', ['warranty'])

guide('maintenance', 'repair-or-replace-decision-log', 'Record Repair-or-Replace Decisions After a Failure', 'Compare a furnishing repair with replacement using safety assessment, complete costs, timing, repeat faults, and fit.',
'''A failed furnishing creates pressure to choose the fastest-looking option. A short decision log helps the manager distinguish a safe repair from a temporary patch and compare the full cost with a suitable replacement. The record also improves future specifications when the same fault recurs.''',
'''First identify the item and the failed function. Remove suspected unsafe equipment from service through the operating process and get appropriate assessment; a cost comparison comes after that boundary. Check recalls, instructions, and written warranty terms. Record whether parts and a qualified repair process are actually available.

Compare complete quotes: assessment, parts, labor, transport, installation, disposal where needed, and the operational effect of waiting. Include the condition of the rest of the item and any repeat faults. A low repair price is not attractive if the result does not restore the intended function or the same cause remains unresolved.''',
'''Hypothetical log: a dining chair develops a structural fault. It is removed from use and assessed. The quoted appropriate repair is $160 including collection and return; a suitable installed replacement is assumed to cost $190. The other matching chairs are inspected, and the owner considers whether the fault is isolated. The decision is documented with the assessment and available options, rather than improvising glue to avoid the $30 difference.''',
'''Identify the product and failed function, photograph the condition, and separate suspected safety issues from cosmetic wear.
Check recall status, product instructions, warranty terms, and the appropriate professional repair route.
Obtain full repair and replacement costs, including handling and installation that apply to the property.
Record parts availability, timing, repeat-fault history, and the remaining condition of the item.
Save the chosen action, responsible person, completion evidence, and any follow-up inspection requirement.''',
'''Recheck the restored function before returning the item to service. Update the inventory and reserve worksheet with actual costs. If several items fail in the same way, review the specification, installation, environment, or use rather than treating each repair as unrelated. The log should make the reasoning visible without predicting the life of every future item.''', ['recalls','warranty'])

guide('maintenance', 'room-reset-photo-standard', 'Create Room Reset Photos That Show Function as Well as Style', 'Document furniture placement, supplies, controls, clean storage, and inspection points with a practical rental reset photo set.',
'''A marketing photo shows a room at its most attractive. A reset photo should show the arrangement the team needs to reproduce every stay. Build a separate operational set that includes controls, storage, supplied items, and functional details that may sit outside a listing camera angle.''',
'''Start with a complete room view, then add close-ups of the bed setup, towel allocation, guest storage, lights, and ordinary controls. Show the exact placement of movable furniture, including a convertible layout if provided. Use item identifiers that match the inventory. Avoid photographing private documents, guest belongings, or access credentials into broadly shared records.

Pair each photo with a short instruction only where needed. “Restore two matching bedside lamps and check both switches” is more useful than a general styling note. Include inspection points for things a photograph cannot establish, such as whether a chair is stable or a lamp works. Pictures complement the reset process; they do not prove cleaning or functionality.''',
'''Hypothetical bedroom set: one wide view records table and luggage-rack positions, one image shows the linen arrangement, and another identifies the clean spare blanket location. A short checklist records the lamp test and curtain operation. When a rack is moved during cleaning, the team can restore the measured location that leaves the wardrobe and door usable. The photos are updated after the new bed frame changes the footprint.''',
'''Capture the completed room and useful close-ups after the functional walkthrough and cleaning process are confirmed.
Show guest-facing supplies, storage, furniture positions, and controls using inventory identifiers where helpful.
Add concise instructions for counts, orientations, or functions that are not obvious in the image.
Keep private access details, personal records, and guest belongings out of widely shared operational photographs.
Assign an owner and version date so the photo standard changes with the installed setup.''',
'''Test the photo set by asking a team member unfamiliar with the design to reset the room. Note where they still need information and simplify the record. Remove obsolete versions from the working set through the normal document process. A useful standard reduces guesswork while leaving the cleaner’s actual inspection and care responsibilities clear.''', ['cleaning'])

guide('maintenance', 'guest-feedback-design-triage', 'Triage Guest Feedback into Repair, Layout or Information', 'Turn repeated furnishing feedback into documented actions with evidence, owners, trial changes, and an accurate guest description.',
'''Not every complaint about a room calls for new furniture. Some point to a broken function, others to an awkward layout or unclear information, and some reflect individual preference. Use a triage log to understand the issue before making an expensive or ineffective change.''',
'''Record the actual feedback without including unnecessary private guest details. Identify the activity affected and any observed condition. Separate repair issues from layout, care, description, and preference. A lamp that does not switch on needs maintenance; a working lamp with a hidden control may need repositioning; a guest who prefers a different light appearance may be reporting preference.

Look for repeated observations while taking potentially unsafe faults seriously immediately through the normal operating process. Assign an owner and a concrete next action. When testing a design change, record comparable conditions and the effect on other functions. Avoid presenting a single positive comment as proof of an uplift in bookings or universal guest satisfaction.''',
'''Hypothetical feedback: several guests mention that bags occupy the bedroom floor. The team checks the room and finds the luggage rack hard to open beside the dresser. Moving it to a tested position resolves the layout conflict. A separate mattress complaint remains a preference question after fit and condition checks; the owner considers a documented trial rather than replacing every bed immediately. Neither action becomes an invented testimonial or a claimed revenue increase.''',
'''Record the guest activity, reported issue, observed condition, and any repetition without retaining unnecessary private details.
Classify the issue as repair, layout, care, information, description, or preference, allowing more than one cause.
Assign an owner and immediate handling for suspected unsafe faults through the established operating process.
Trial a focused change and check how it affects cleaning, circulation, storage, and other guest activities.
Close the action with evidence and update the inventory, reset standard, or guest description where relevant.''',
'''Review the log during planned condition checks so repeated minor problems are not lost in individual messages. Share practical findings with the designer when planning the next property, while keeping client and guest records private. The goal is a visible feedback-to-action process grounded in what happened, not a collection of promotional claims about the design.''', ['warranty'])
