from content.host_guides import guide

guide('materials', 'upholstery-care-label-brief', 'Turn Upholstery Care Labels into a Cleaning Brief', 'Create a sofa and chair care brief from the exact fabric label, approved products, drying instructions, and cleaner feedback.',
'''A fabric marketed as easy to clean can still require a process your turnover team cannot perform. Before approving upholstered furniture, find the instructions for the actual fabric and construction. Convert those instructions into a short care brief that stays with the item, rather than relying on a general promise about performance upholstery.''',
'''Record the fabric name, color, item model, and care-label photograph. Ask the supplier what routine cleaning and spot treatment are permitted, whether covers can be removed, and how drying works. A removable cover is not automatically machine washable. A water-resistant fabric is not necessarily compatible with every cleaner, and the foam or seams may need different treatment.

Give the cleaner the actual instructions and ask about equipment, drying time, and access. If instructions are missing or contradictory, get written clarification before buying. Sunbrella’s published care guidance is an example of a manufacturer-specific resource; it should not be applied to a different fabric simply because both are described as outdoor or performance materials.''',
'''Hypothetical approval trial: two similar beige sofas are shortlisted. One has washable cushion covers but a fixed back requiring specialist care. The other allows replacement of both seat and back covers, though each must be cleaned according to its own instructions. The local team can handle the first sofa’s removable covers, but cannot support its fixed-back cleaning between closely spaced stays. The owner asks for a specialist plan or chooses another specification rather than assuming a spray cleaner will solve every stain.''',
'''Photograph the item label and save the supplier’s exact fabric and furniture care documents together.
Confirm routine vacuuming, permitted spot treatment, cover removal, and drying instructions for every component.
Ask the local cleaner to identify equipment needs and practical turnaround constraints before approving the fabric.
Test a spare sample using the approved process and record any color, texture, or finish change.
Store the approved products and instructions where the team can find them, with an escalation contact for uncertain stains.''',
'''At installation, label removable covers discreetly so the right piece returns to the right cushion. Keep a record of cleaning incidents and their outcomes. Do not add an unapproved stain treatment to the brief based on a social-media tip. If the supplier changes the fabric or cover construction during a substitution, repeat the care review; the earlier approval may no longer apply.''', ['fabric','cleaning'])

guide('materials', 'sofa-construction-inspection', 'Inspect Sofa Construction Beyond the Fabric Rating', 'Compare sofa frame details, seams, cushion support, connectors, service access, and replacement parts before approval.',
'''An upholstery abrasion rating describes one aspect of the fabric. It does not tell you whether a sofa’s joints, cushion support, seams, or legs will remain serviceable. Compare the complete piece of furniture, especially when it will be moved for cleaning or used frequently by different guests.''',
'''Ask for frame construction, joint details, leg attachment, cushion composition, and the manufacturer’s intended-use information. Examine a sample where possible. Look for secure connectors, consistent seams, accessible hardware, and cushions that retain their position during ordinary sitting. Check how loose cushions are removed and whether sectional pieces separate unintentionally during use.

Review the written warranty and any exclusions relevant to your use. A long headline warranty may apply only to the frame while excluding covers, labor, or delivery. Check replacement cushions and covers by exact model, color, and version. Do not infer overall furniture life from a fabric test or describe a chair as commercial grade without evidence for that actual product.''',
'''Hypothetical comparison: sofa A and sofa B advertise similar fabric durability. A has a replaceable seat cushion, accessible leg fasteners, and a written parts process. B has a sealed base and no replacement cushion listing. If B’s seat compresses, the owner may have to replace the entire sofa. A can still be the wrong choice if it is uncomfortable or too large; the construction review adds evidence to the decision rather than selecting a winner automatically.''',
'''Request frame, support, cushion, connector, and intended-use details for the exact model being quoted.
Inspect ordinary seating comfort, seam alignment, cushion movement, and visible assembly quality on a sample if available.
Confirm how legs and sectional connectors are serviced without damaging the surrounding upholstery.
Read the actual warranty and separate coverage of frame, cushions, fabric, labor, and transport.
Verify replacement part identifiers and ordering procedures instead of assuming a matching part will exist later.''',
'''Save the assembly instructions with the inventory and give the maintenance team approved inspection points. If a connector, joint, or support looks damaged, remove the affected furniture from use until it is assessed. Do not improvise structural repairs. A practical specification combines comfort, fit, cleanability, and serviceability; no single fabric number substitutes for that review.''', ['warranty','recalls'])

guide('materials', 'removable-cushion-replacement-plan', 'Specify Replaceable Cushions and Covers Before Buying', 'Plan cushion and cover replacement using exact part identifiers, cleaning instructions, storage needs, and reorder confirmation.',
'''Replaceable cushions can make a furnishing easier to maintain, but only when the parts are obtainable and the team knows what fits. “Removable” describes how a cushion comes off the sofa. “Replaceable” requires a compatible part, a purchase process, and enough information to order it correctly.''',
'''Ask the vendor for separate identifiers for seat inserts, back inserts, and covers. Record dimensions and which cushions occupy which positions. A left-hand sectional cushion may differ from a right-hand cushion even when the fabric looks identical. Confirm whether replacement parts are stocked, made to order, or unsupported, and save the written response with the purchase record.

Consider a spare only after estimating the actual storage and likely need. Store it clean and dry using appropriate care instructions, and keep it protected from compression or pests. An extra cover can address one kind of damage; it will not repair a collapsed insert or structural fault. Avoid mixing inserts of unknown size or firmness merely because they can be squeezed into the same cover.''',
'''Hypothetical specification: a three-seat sofa uses two outer seat cushions and one differently shaped center cushion. The order record lists each part separately. The owner purchases one extra center cover because that piece is difficult to reorder, while the inserts remain available through the supplier. A labeled photo shows orientation. During a reset, the cleaner can identify the right replacement without treating the spare as a universal cover for the entire sofa.''',
'''Confirm whether covers, inserts, and the surrounding furniture are separately serviceable for the quoted product version.
Record part identifiers, dimensions, color codes, orientation, and photographs of each distinct cushion position.
Ask how parts are ordered, what compatibility information is required, and whether availability is promised or merely current.
Size the storage space before buying spares and follow the product’s storage and care instructions.
Create a replacement record so the date, reason, and fitted part are visible to the next team member.''',
'''Recheck the part plan if the furniture model changes before dispatch. At installation, compare actual labels with the order. If a spare does not fit properly, hold it aside and resolve the mismatch rather than forcing it into use. Feed real replacement frequency into the reserve worksheet so spare purchases become evidence-based and do not grow into an unused closet of incompatible components.''', ['warranty','fabric'])

guide('materials', 'wood-veneer-edge-care', 'Evaluate Wood and Veneer Furniture at the Edges', 'Inspect furniture edges, joints, finish instructions, and repair options where daily rental use can expose weaknesses.',
'''The center of a tabletop is easy to photograph. Edges, feet, joints, and undersides often reveal more about how a piece can be maintained. When comparing wood, veneer, and composite furnishings, look at the complete construction rather than treating a material name as a guarantee of durability.''',
'''Inspect where guests grip, bump, drag, or place wet items. Look at edge finishing, exposed substrates, leg attachments, and joints around drawers. Ask the manufacturer which cleaners and moisture exposure are acceptable. “Solid wood” does not mean waterproof, and veneer can be a reasonable option when its construction and intended use match the room.

Request the repair approach before approving an expensive piece. A finish specialist may be able to repair a surface but not conceal damaged edge banding. Check whether a drawer runner or leg can be replaced independently. On existing furniture, distinguish finish wear from swelling, cracking, or instability. Those conditions need their own assessment, not a coat of decorative paint.''',
'''Hypothetical bedside-table comparison: a veneered unit has a well-finished top but an exposed underside edge beside the floor. A solid-wood alternative has a delicate finish that the supplier says needs careful moisture protection. The room is small and the cleaner frequently moves the tables to vacuum. The owner compares edge exposure, weight, floor protection, approved cleaning, and repair support before choosing; neither material label alone decides the purchase.''',
'''Inspect top, edge, underside, drawer, and leg details on the actual sample or detailed supplier photographs.
Read the finish-specific care instructions and identify likely water, heat, and cleaning exposure at the proposed location.
Confirm whether hardware and moving parts can be accessed and replaced without destroying the furniture.
Ask a qualified repair provider about the likely repair method if a high-value finish is damaged.
Record condition at installation and choose floor protection that is compatible with both furniture and flooring.''',
'''Give the cleaner the approved process and avoid applying oil, polish, solvent, or abrasive pads without product guidance. Place coasters or trays where they are useful, but do not use them to excuse a poor specification. If an edge swells or a joint moves, document it and assess the cause before patching the visible symptom. Moisture problems may require attention beyond the furniture.''', ['warranty','moisture'])

guide('materials', 'rug-size-laundry-capacity', 'Match a Washable Rug to Your Actual Cleaning Capacity', 'Check rug dimensions, machine capacity, drying, furniture movement, and replacement logistics before specifying a washable rug.',
'''A washable rug can still be difficult to maintain at a rental. The cover may not fit the available machine, take longer to dry than the reset allows, or require moving heavy furniture. Approve the rug as part of a cleaning system rather than relying on the word washable in a product title.''',
'''Read the exact rug care instructions and any machine-capacity requirements. Separate the cover from the backing or pad: they may need different methods. Check whether the local machine can handle that size and construction under its own instructions. Do not substitute a home-machine estimate for the manufacturer’s limits. Include drying location and drying time in the operational review.

Test the rug in the room with doors, chair legs, and vacuum equipment. A thin rug can still curl at an edge or move when chairs are pulled out. Select a compatible pad and secure placement according to product guidance. If an entire seating group must be disassembled to remove the rug, routine washability may have little practical value.''',
'''Hypothetical room plan: an 8-by-10-foot cover would require an off-site laundry process according to the supplier and local cleaner. A smaller option fits the room less well but is manageable with the available equipment. The owner chooses the larger rug only after arranging an off-site clean and a suitable spare cover, or selects a different material with a supported cleaning plan. The decision includes the actual removal route and storage space, not just the initial rug price.''',
'''Confirm care instructions separately for cover, backing, and pad, including permitted machine and drying methods.
Check the equipment requirements with the cleaner and machine instructions for the exact rug size.
Test doors, chair movement, edge behavior, and vacuum access with the rug installed in its intended position.
Time a real removal and reset trial so furniture movement is included in the cleaning plan.
Define what happens when the rug cannot be cleaned and dried before the next arrival.''',
'''Keep the rug model and size with the inventory. If washing changes its fit or the edges do not lie flat, reassess placement before guest use. A second cover needs clean, dry storage and a matching version. Review real cleaning costs and condition during maintenance checks; a washable label does not establish a fixed number of washes or guarantee an easier turnover.''', ['shopping','cleaning'])

guide('materials', 'dining-finish-sample-test', 'Use a Finish Sample to Choose a Rental Dining Table', 'Evaluate a dining tabletop using finish instructions, realistic spill handling, cleanability, and a controlled sample comparison.',
'''A dining table experiences more than a staged place setting. Guests may serve hot meals, wipe spills, move dishes, and use the same surface for work. A finish sample can help you compare appearance and approved cleaning under the conditions the property will actually support, without damaging a showroom piece.''',
'''Ask for the exact finish specification and a spare sample if available. Establish what the manufacturer allows for cleaning, heat, and moisture. Do not conduct destructive tests on the purchased furniture or assume a sample represents a different finish. Have the turnover team use the approved cleaning process on the sample and judge the result in daylight and artificial light.

Consider glare, fingerprints, seams, and edges alongside stain removal. A deeply textured top may hide minor marks but require extra cleaning around grooves. A glossy top can be easy to wipe yet show reflections in the room. Check repair options and whether a table leaf creates a seam the team can inspect and clean.''',
'''Hypothetical comparison: two supplier samples are evaluated using permitted routine cleaning after an ordinary food spill is promptly wiped. Sample A shows every fingerprint under the proposed pendant. Sample B has a quieter appearance but a beveled seam that catches crumbs. The team records those tradeoffs and chooses the table after confirming the seam can be cleaned efficiently. This trial is an original selection exercise, not a certified durability test or a promise that future spills will leave no marks.''',
'''Request the finish name, care instructions, intended-use information, and a sample matching the actual order.
Use only an approved sample-cleaning process and record the products, conditions, and observations.
Inspect glare, fingerprints, seams, edges, and the underside where routine wiping or movement may reach.
Ask about refinishing, replacement leaves, and repair support before deciding on an expensive surface.
Approve practical table protection and storage for mats or coasters without overstating what they can prevent.''',
'''Save a labeled spare sample and the approval notes. During handover, show the cleaner which products are permitted and where spill instructions are stored. If the delivered finish differs from the sample, resolve the mismatch before treating the earlier trial as valid. Tables still need ordinary care even when the sample performs well; the result is evidence for selection, not an indestructibility claim.''', ['warranty','cleaning'])

guide('materials', 'paint-touch-up-record', 'Build a Paint Finish and Touch-up Record', 'Track paint product, color, sheen, wall location, application notes, and repair samples for consistent rental touch-ups.',
'''A color name alone is not enough to reproduce a painted wall. Product line, sheen, surface preparation, and application can affect the result. Create a room-by-room paint record during a refresh so the maintenance team can make a deliberate repair instead of applying whatever white paint is left in a cupboard.''',
'''Label each painted surface with the manufacturer, product, color identifier, sheen, and application date. Keep the actual container label or invoice and record any custom mix. Note which surfaces are different: walls, trim, ceilings, doors, and damp-area finishes. Benjamin Moore’s finish guide is useful background on sheen choices, but use the instructions for the particular product selected.

Test a small repair in a discreet area according to the product instructions. A touch-up can look different because of aging, texture, or application even when the label matches. Decide when a whole wall needs repainting to avoid a patchwork appearance. Respect curing and cleaning instructions; a freshly painted surface is not automatically ready for vigorous wiping.''',
'''Hypothetical handover: the living room uses one product in an eggshell finish, while the trim uses another in satin. The record includes wall labels and container photos. When a small scuff appears, the maintenance person first uses the permitted cleaning method, then tests a touch-up if needed. The test flashes visibly under the side light, so the owner approves repainting that wall rather than adding several mismatched patches across it.''',
'''Record manufacturer, product line, color or custom formula, sheen, and the surface each finish covers.
Photograph labels and save invoices before paint containers become illegible or are discarded through the proper process.
Note preparation, primer, application date, and any relevant product curing or cleaning instructions.
Store any retained paint according to its label and local requirements, away from guest access.
Test discreetly and define who approves a whole-wall repaint when a local touch-up remains visible.''',
'''Update the record after every repaint, including a sheen or product change that seems minor. Do not paint over dampness or an unresolved surface problem to improve the photo. Diagnose the cause and use an appropriate professional when needed. Keep paint records with the wider material schedule so a new cleaner or maintenance provider can understand what is actually installed.''', ['paint','moisture'])

guide('materials', 'bathroom-accessory-cleanability', 'Choose Bathroom Accessories the Cleaner Can Reach', 'Evaluate soap dispensers, hooks, shelves, trays, and storage for cleanability, drying, installation, and everyday guest use.',
'''Bathroom accessories often appear late in a design plan, yet they are touched and cleaned every stay. A sculptural tray or hard-to-open dispenser may photograph well while adding work or confusing guests. Choose these details with the person who will refill, dry, and reset them.''',
'''Map the tasks first: hand washing, towel drying, toiletries, waste disposal, and wet-item storage. For each accessory, check stability, reachable placement, cleanable surfaces, and how it opens. A wall-mounted item may free counter space but needs suitable installation and a plan for cleaning behind it. Avoid drilling or mounting without checking the wall assembly and appropriate fixing method.

Keep the number of decorative objects proportional to the counter space. Specify product materials and care instructions; metal color names do not tell you how a finish tolerates a cleaner. Choose a drying arrangement that separates wet towels from stored dry linens. Persistent condensation or dampness needs a moisture response beyond changing accessories.''',
'''Hypothetical compact bathroom: a large tray leaves little counter area beside the basin and traps water underneath. The revised plan uses a stable dispenser, a small guest-items shelf in a suitable location, and individually placed towel hooks with room for towels to hang. The cleaner can lift or reach every component and identifies a dispenser that can be refilled without a special tool. The owner tests the arrangement after an ordinary shower before approving the reset photograph.''',
'''List the actual bathroom tasks and allocate space for guest toiletries as well as supplied products.
Check how dispensers open, drain, and refill, including access to their interior cleaning surfaces.
Confirm appropriate mounting, load limits, and care instructions for each accessory and finish.
Test towel spacing and drying locations without placing wet items against stored linens or sensitive surfaces.
Ask the cleaner to perform a full reset and record any inaccessible seams, trapped water, or extra handling.''',
'''Save accessory models and replacement information with the bathroom inventory. Keep refills organized according to their labels and the manager’s process. If a finish deteriorates, investigate the product and cleaning compatibility before buying an identical replacement. Clear, accessible surfaces and a tested routine are more valuable than an overcrowded display of objects that cannot be maintained efficiently.''', ['moisture','cleaning'])
