from content.host_guides import guide

guide('outdoors', 'outdoor-exposure-map', 'Map Sun, Rain and Wind Before Buying Patio Furniture', 'Create an outdoor exposure map that connects guest activities, product suitability, loose-item storage, and local reset procedures.',
'''An outdoor furniture specification should start with the site, not a coordinated product collection. Sun, driving rain, wind, salt, irrigation, and ground conditions can affect different parts of the same patio. Map those exposures at the times guests are likely to use the space before selecting furniture or textiles.''',
'''Draw the usable area, entrances, fixed equipment, planting, and places where water collects or wind is noticeable. Visit at representative times and note that a single visit does not describe every season. Ask the local manager about conditions they observe. Separate a guest’s comfortable sitting area from the handling and storage needed when conditions change.

Check the actual furniture and textile instructions for the proposed location. “Outdoor” is not a promise of unlimited exposure or zero maintenance. Verify anchoring or mounting through appropriate product instructions and professionals where needed. Keep movement and storage practical; a weather procedure that requires equipment the team does not have will not be reliable.''',
'''Hypothetical patio: the wall-side seating is shaded during breakfast, while the center receives direct afternoon sun and occasional wind-driven rain. Loose cushions can be stored in a dry indoor location, but the proposed oversized sectional cannot be moved by the usual team. The owner compares smaller serviceable pieces and the actual exposure guidance rather than assuming the most substantial-looking set is the best fit.''',
'''Map outdoor activities, entrances, drainage observations, fixed equipment, and the locations proposed for furniture.
Observe representative conditions and combine the visit with the local manager’s seasonal experience.
Check product suitability and care instructions for the actual sun, moisture, wind, and salt exposure.
Define how loose items are handled and where they can be stored clean and dry.
Confirm appropriate mounting or other technical work and document the local reset owner and process.''',
'''Keep the exposure map with the outdoor inventory and revisit it when shade, planting, or drainage changes. During a seasonal handoff, compare observed conditions with the original assumptions. If a product deteriorates, investigate exposure and care before ordering the same replacement. The map guides selection and maintenance; it does not certify the site against every weather condition.''', ['fabric','moisture'])

guide('outdoors', 'outdoor-cushion-drying-storage', 'Give Outdoor Cushions a Drying and Storage Workflow', 'Plan cushion identification, approved cleaning, complete drying, clean storage, reset ownership, and weather handoffs.',
'''Outdoor cushions need more than a storage box. They need a process for inspection, approved cleaning, drying, and return to service. Closing damp cushions inside a container can preserve the moisture problem instead of solving it. Specify the workflow while choosing the seating and textile system.''',
'''Read the instructions for cover, insert, and furniture separately. Some covers can be removed; some cannot, and permitted drying methods differ. Sunbrella’s care resources show why exact fabric guidance matters, but they should not be transferred to another material without support. Ask the local team how they will handle and dry the actual cushions.

Allocate space for the full quantity and label distinct shapes or positions. Choose storage that matches product guidance and local conditions. Separate clean, dry stock from wet or uncertain-condition items. Assign responsibility for checks after weather exposure and before guest arrival rather than relying on guests to perform the property’s maintenance process.''',
'''Hypothetical six-cushion patio set: two corner cushions are shaped differently. Each is identified in a simple placement photo. After rain, the manager follows the approved handling and drying instructions in a suitable location. Only fully ready cushions return to the clean storage area. A damaged cover is matched to the specific part record instead of replaced with a similarly colored but incompatible cushion.''',
'''Record instructions for the exact covers, inserts, and supporting furniture, including permitted drying methods.
Identify different cushion shapes and store their placement and part information with the inventory.
Provide sufficient handling and drying space for the full set under the local operating process.
Keep clean, dry cushions separate from wet, soiled, or uncertain-condition items until they are ready.
Assign checks and reset ownership after exposure, between stays, and during seasonal storage.''',
'''Trial the complete workflow with the people who will perform it. If the space or turnaround is impractical, adjust the seating specification before installation. Recheck after changing covers, inserts, or storage containers. Do not describe the patio as maintenance-free because a fabric repels an initial spill; the whole cushion system and its environment remain part of the care plan.''', ['fabric','moisture'])

guide('outdoors', 'coastal-metal-care-record', 'Keep a Coastal Furniture Hardware and Finish Record', 'Track outdoor metal finishes, fasteners, approved care, exposure, and specialist assessment at a coastal rental.',
'''At a coastal property, outdoor furniture maintenance depends on actual exposure and construction. Metal color or a powder-coated appearance does not establish how the entire item will tolerate salt, moisture, and repeated handling. Keep a finish and hardware record so inspections lead to the right care or assessment.''',
'''Record the frame material, finish, hardware details, and supplier instructions for the exact product. Ask about suitability for the site and exclusions in written warranty terms. Fasteners, connectors, and hidden components can differ from the visible frame. Do not assume a supplier’s description of one part applies to every component.

Use the permitted routine care process and inspect joints, contact points, and damage to finishes. Avoid improvising abrasive treatment or coatings without product guidance. If corrosion, looseness, or structural concern appears, remove the affected item from use and obtain appropriate assessment. A cosmetic touch-up should not conceal a condition that affects function.''',
'''Hypothetical coastal dining set: the frame finish looks intact from a distance, but inspection finds deterioration around a connector. The manager photographs it, checks the product record, and asks the supplier or appropriate repair provider for assessment. Another piece has only a documented cosmetic mark addressed through approved care. The log separates those cases rather than treating every visible change as harmless surface wear.''',
'''Record materials, finish, hardware, intended location, and the exact manufacturer’s care guidance at purchase.
Confirm site suitability and any exposure-related limitations in the written product or warranty information.
Inspect visible and accessible joints, contact areas, and finish damage during the approved maintenance process.
Use only supported care or repair methods and seek assessment for corrosion or structural concerns.
Save photographs and actions by item so recurring deterioration informs the next specification.''',
'''Use local experience to set inspection and care scheduling instead of publishing a universal coastal maintenance interval. Review actual failure patterns before replacing items with the same model. Keep service records with the inventory and communicate changes to the reset team. The aim is an informed care process for this installed product, not a claim that one metal is immune to the environment.''', ['warranty','fabric'])

guide('outdoors', 'shade-furniture-coordination', 'Coordinate Shade with the Furniture Guests Actually Use', 'Test outdoor seating and dining at relevant times while reviewing shade-product installation, controls, storage, and maintenance.',
'''Shade on the plan may not cover the seats guests use at the time they use them. Evaluate the outdoor activity and sun position together before approving furniture and a shade product. A photograph of an open umbrella at one hour is not a complete specification.''',
'''Map breakfast, midday, and evening uses and observe the available shade. Test chairs and tables in ordinary positions, including the route around the base or supporting structure. Confirm the shade product’s installation, suitable supporting components, operating limits, and storage instructions. Use the appropriate professional for fixed structures or technical work.

Avoid treating a heavy-looking base as proof that an umbrella can remain deployed in all conditions. The operating procedure must follow the actual product guidance and local assessment. Assign who handles adjustment, inspection, closure, and storage. Guests can receive clear ordinary instructions, but the maintenance plan should not rely solely on their judgment.''',
'''Hypothetical dining patio: shade covers the tabletop during a midday visit but leaves two chairs exposed when pulled out. A different tested arrangement improves useful coverage while preserving the entrance route. The proposed umbrella support interferes with chair movement, so the owner reviews a suitable alternative. The final plan includes the product’s operating and storage process rather than calling the outdoor dining area continuously shaded.''',
'''Observe shade at the times the property’s outdoor activities are likely to occur, noting seasonal limitations.
Test the actual seating positions, chair movement, table use, and routes around supports or bases.
Confirm product installation, component compatibility, operating limits, and storage through exact instructions.
Assign local responsibility for inspection, operation, and weather-related handling.
Describe the installed shade provision accurately and retain the approved setup in outdoor reset photographs.''',
'''Recheck after moving the furniture, replacing the shade product, or changing landscaping. If conditions exceed the supported use, follow the operating plan rather than trying improvised weights or tie-downs. Record issues in the outdoor condition log. Practical coverage, clear ownership, and appropriate installation matter more than a perfectly coordinated collection shown in a single photograph.''', ['warranty','shopping'])

guide('outdoors', 'small-balcony-functional-plan', 'Plan a Small Balcony Around One Clear Guest Activity', 'Choose a realistic balcony use with door operation, seating movement, cleaning, building constraints, and loose-item handling.',
'''A small balcony can support a useful morning coffee spot or a compact sitting area without pretending to be an outdoor living room. Choose the primary activity first, then test it within the actual space and the property’s building requirements. More furniture can remove the very route that makes the area usable.''',
'''Draw the door’s operation, fixed elements, and the proposed furniture. Test entry with chairs occupied and pulled out, not only folded or tucked under the table. Keep items from creating climbable arrangements or interfering with required safety features; obtain appropriate review for concerns. Check building or association constraints through the owner’s normal process before mounting or altering anything.

Choose products suited to the exposure and a cleaning arrangement the team can perform. Plan where loose cushions and small objects go when conditions change. Avoid fixtures, planters, or décor that depend on unsupported attachment to a railing. The public description should show the actual use and limits of the area.''',
'''Hypothetical balcony: a proposed three-piece lounge set prevents the door from opening fully once guests sit down. The design instead trials two suitable compact chairs and a small table for coffee, while retaining clear access and cleaning reach. The owner reviews building restrictions and installation conditions before approving any wall or railing accessory. The listing shows the compact sitting arrangement rather than calling it a full outdoor dining space.''',
'''Select the main activity and confirm applicable building or association constraints before purchasing furnishings.
Test door operation, entry, and chair movement with the proposed furniture in normal use.
Review placement near safety features and obtain appropriate professional assessment where needed.
Check exposure suitability, cleaning access, and supported handling of loose items.
Use an accurate description and a reset photo that preserves the confirmed arrangement.''',
'''Revisit the plan if guests regularly move furniture or leave items in the doorway. Remove unnecessary objects before sacrificing access. Any mounting or structural change should follow the appropriate review rather than a decorative installation shortcut. A successful compact balcony is one that performs its chosen activity clearly and can be maintained, even when that means a deliberately small furnishing set.''', ['routes','shopping'])

guide('outdoors', 'seasonal-outdoor-handoff', 'Create a Seasonal Outdoor Furniture Handoff', 'Record cleaning, condition, storage, missing parts, approved reopening tasks, and responsibility when outdoor furnishings change season.',
'''Seasonal storage is a small project of its own. Furniture moved out of sight can lose hardware, retain dampness, or return to service without inspection. Create a handoff record that tells the next team exactly what was stored, its condition, and what must happen before reopening the area.''',
'''Inventory items by product and location, then follow their approved cleaning and storage instructions. Record parts removed during supported disassembly and keep them labeled with the item. Photograph condition before storage and flag anything that needs repair or specialist assessment. Do not pack wet or unsuitable items into the clean-storage stock.

Check that the planned location can accommodate the quantity and handling process. Separate guest items, cleaning supplies, and owner storage appropriately. Assign reopening tasks: inspection, assembly according to instructions, placement, function checks, and updated photos. If an amenity is unavailable seasonally, the manager should keep the listing and guest information accurate through the normal operating process.''',
'''Hypothetical handoff: a patio table, four chairs, and six labeled cushions move to their approved storage locations. A missing connector is recorded before packing rather than discovered at spring reopening. The responsible person orders the correct part and arranges supported assembly. The manager verifies the reopened layout and updates the available-amenity description only after the set is ready for use.''',
'''List every stored furnishing with its identifier, count, condition, and planned location.
Follow product-specific cleaning, drying, disassembly, and storage instructions before packing.
Label any removed parts and keep the assembly documents connected to the item.
Assign repair, reopening, inspection, and placement tasks to named responsible people.
Reconcile the listing and guest information with the actual seasonal availability of the outdoor space.''',
'''Use the same record at closing and reopening so missing items and unresolved faults remain visible. Review unused or repeatedly damaged pieces before buying more seasonal décor. If the storage plan fails in practice, change the specification or location rather than repeating it. Seasonal handover should restore a working outdoor experience, not simply return every object to the photograph.''', ['fabric','warranty'])

guide('outdoors', 'sand-mud-transition-design', 'Design the Transition from Sand or Mud to Clean Rooms', 'Plan outdoor gear landing, shoe handling, drying, washable surfaces, and reset ownership without sacrificing the entrance route.',
'''Sand and mud enter where guests naturally change activities. Plan that transition at the property’s actual entry rather than expecting a decorative sign to change behavior. A useful arrangement gives guests somewhere obvious to handle shoes and gear while keeping the entrance and clean belongings usable.''',
'''Observe the route from outdoor activity to the door, including where guests can sit, set bags, and leave wet items. Choose mats, trays, or storage according to their care and exposure instructions. Check movement and trip concerns in the installed arrangement. A mat that wrinkles, moves, or blocks the door is not a successful transition detail.

Separate dry luggage and clean towels from footwear and wet equipment. Provide an appropriate cleaning process for the supplied items and the adjacent floor. If a rinse facility is part of the plan, its plumbing, drainage, local suitability, and installation require the responsible professional’s review. Do not add an improvised water source as a furnishing shortcut.''',
'''Hypothetical beach rental: guests carry sand through the hall because the shoe location is behind an interior door. Moving the supported shoe-handling area to a clear arrival position makes the intended use obvious. The team checks the mat with the entrance open and wet gear present. Clean beach towels remain in a separate dry location, and the reset log assigns tray cleaning and drying rather than leaving residue for the next stay.''',
'''Map the actual activity-to-entry route and identify the first practical place for shoe and gear handling.
Choose supported mat, tray, or storage products and test them with the door and route in use.
Separate wet or dirty items from dry luggage, clean stock, and sensitive furnishings.
Confirm any plumbing or technical work through the appropriate professional and local operating review.
Assign cleaning, drying, inspection, and replacement tasks in the transition-area reset record.''',
'''Trial the arrangement during representative use and ask the cleaner where sand or mud still accumulates. Adjust placement and capacity before adding more instructions. Recheck when the guest activity or season changes. The goal is to make the useful behavior easy and maintainable; the design should not depend on every guest reading a long set of rules before entering.''', ['moisture','cleaning'])
