"""Provider-authored service information checked October 6, 2026.
Unknown terms stay unknown. Editorial questions are separate from sourced facts.
"""
COMPANIES=[]
def add(slug,name,kind,design,execution,coverage,pricing,question,source):
 COMPANIES.append(dict(slug=slug,name=name,kind=kind,design=design,execution=execution,coverage=coverage,pricing=pricing,question=question,source=source,checked='2026-10-06'))
add('str-cribs','STR Cribs','STR design and renovation company','Rental design paired with renovation and amenity work.','The site presents design and renovation as a combined project offering. Confirm contractors, procurement and installation in the proposal.','Advertises nationwide service; confirm the exact property and site work.','Request an itemized design, renovation and furnishing proposal.','Which work requires a contractor, and who owns permitting, installation and the final punch list?','https://www.strcribs.com/')
add('showplace','Showplace','Rental design and furnishing service','Designer collaboration, mood boards and digital room renderings.','Its process offers installation bids ranging from host installation to white-glove service.','Describes its service as nationwide. Confirm installation availability at the address.','Request design, furniture and installation costs separately.','Which installation bid is included, and who receives and inspects the furniture?','https://www.showplacehq.com/')
add('somerled-designs','Somerled Designs','STR strategy and design studio','Virtual design with market research, layouts and sourcing documentation.','Project Management adds procurement, delivery coordination, on-site installation and photo staging.','The current service page describes U.S. project management and worldwide virtual design.','The provider discusses a recommended budget during consultation.','Are you quoting Virtual Design or Project Management, and what is the signed handoff date?','https://www.somerleddesigns.com/work-with-us')
add('str-refresh','STR Refresh','STR design and setup service','Lists interior design, furnishing, redesign and virtual design scopes.','Turnkey setup covers design, furnishing, installation, styling and photo-ready staging.','Advertises work with owners and investors across the United States.','Request a quote for the specific listed scope.','Is the assignment a refresh of an operating rental or a complete new-listing setup?','https://strrefresh.com/services')
add('magic-interiors','Magic Interiors','Vacation-rental design and installation company','Offers virtual design and custom themed vacation-rental interiors.','Nationwide installs combine local assembly of large custom pieces with its design team’s on-site finishing.','Advertises U.S. design and installation; hand-painted murals and management are limited to its Florida markets.','Its nationwide page says freight and team travel are added to the project budget.','Which custom elements travel, and which labor, freight and team travel costs are included?','https://magicinteriorsusa.com/nationwide/')
add('belo-home-styling','Belo Home Styling','Vacation-rental decorating and furnishing service','A room-by-room lookbook and item list are reviewed before ordering.','Describes ordering, shipping arrangements, assembly and decorating as part of its process.','Names Austin, San Antonio, Dallas, Houston and Port Aransas, and also advertises nationwide service.','Request a property-specific furnishing and service quote.','Does the proposed installation plan cover your exact market and the complete room inventory?','https://belohomestyling.com/')
add('bee-setups','Bee Setups','Rental design and turnkey setup service','Lists Standard, Essentials, Premium and Luxury design packages with different revision allowances.','Its packages describe sourcing, delivery, assembly and setup; higher tiers list additional scope.','The packages page addresses short-term, mid-term and investment rentals. Confirm the property’s service area.','Published package fees start at $995 plus furniture cost; eligibility and complete costs need confirmation.','Which tier applies to the property, and what furniture, exterior work and extra charges are excluded?','https://www.beesetups.com/packages')
add('well-hosted-design','Well Hosted Design','Short-term-rental design studio','Positions its design and furnishing selection around budget-conscious rental hosts.','The site describes refresh and renovation projects. Ask for the exact purchasing and on-site execution responsibilities.','The reviewed homepage does not establish an installation service area. Confirm coverage directly.','Request a package and execution quote for the property.','Does your package stop at design selections or include buying, receiving and installation?','https://www.wellhosteddesign.com/')
add('curated-designs-studio','Curated Designs Studio','Residential and STR interior design studio','Lists styling, furniture selection, layout work and flexible design services.','The site describes turnkey STR projects and renovation-related work. Confirm the contracted execution tasks.','Headquartered in Dallas/Fort Worth; its site invites projects beyond DFW. Confirm site availability.','Request a scope-specific design and execution proposal.','Will the assignment include floor-plan development, furnishing execution or both?','https://www.curateddesigns.com/')
add('becky-jones','Becky Jones','Short-term-rental design service','Virtual Design includes design boards, an ordering spreadsheet and installation instructions.','Design & Install adds ordering, receiving, installation and styling; the service page also describes listing photos.','Confirm virtual and installation availability for the property; no blanket coverage assumption is made here.','The service page invites a consultation and proposal.','Which installation and photo deliverables are included beyond the ordering spreadsheet?','https://www.beckyjonesbranding.com/services')
add('the-nested-company','The Nested Company','STR design and implementation company','Design Plan includes space planning, furnishing specifications and a room-by-room implementation plan.','The service page contrasts the owner-implemented plan with fully managed procurement and white-glove installation.','Design Plan is advertised nationwide; confirm managed implementation coverage.','Design Plan is listed from $4 per square foot with a $3,500 minimum. Request current total scope costs.','Are the same rooms and guest amenities covered in the plan-only and managed proposals?','https://www.thenestedcompany.com/services')
add('vacay-rental-design','Vacay Rental Design','Vacation-rental design service','The packages page offers design support for short-term-rental interiors.','Lists a full-service design and installation option called Concierge, Please.','Confirm whether the chosen package is available at the property’s location.','Request a quote for the selected package and included execution.','Does Concierge include receiving, freight, assembly and listing photography at your property?','https://vacayrentaldesign.com/packages')
add('sol-vibe-design','Sol Vibe Design','Vacation-rental interior design service','Offers sourcing help, design advice and rental-specific furnishing packages.','Describes a Turnkey Concierge Full-Service Package and renovation-related product sourcing.','Confirm location eligibility and which services are remote versus on site.','Request a proposal identifying design fees and the furnishing level selected.','Who handles the renovation work, and how is it separated from furnishing and design?','https://www.solvibedesign.com/services/short-term-rental-design')
add('amenistays','AmeniStays','STR design service','Virtual packages list plans, shopping links and step-by-step installation guidance.','Full-Service STR Design lists sourcing, on-site installation, styling, photo-ready staging and project management.','Remote-friendly packages are listed; confirm on-site coverage for the address.','Request the current virtual or full-service package quote.','What responsibilities stay with your local team if you choose the virtual package?','https://amenistays.com/design/')
add('michael-interieurs','Michael Intérieurs','Residential and short-term-rental interior studio','Offers an STR virtual plan and shoppable furnishing list.','Its turnkey STR scope lists design, sourcing, installation, cleaning and photography.','The site includes Florida market pages and remote services. Confirm the specific project location.','STR Virtual & DIY is listed from $4,000 and Turnkey from $8,700; request applicability and exclusions.','Does the quoted turnkey price include furniture, cleaning and photography for this property size?','https://michaelinterieurs.com/')
add('erica-ooh-designs','Erica Ooh Designs','Vacation-rental strategy and design studio','Virtual Design includes strategy, design, sourcing and a purchase list.','Full-Service Design describes ordering, consolidated receiving, installation and photoshoot styling.','Virtual design uses the owner’s team for delivery and installation. Confirm full-service market eligibility.','Lists virtual design fees from $8,750 and full-service fees from $17,850, with furnishings and other costs separate.','How much is the total beyond the design fee, including receiving and installation labor?','https://ericaooh.com/')
add('on-design-interiors','On Design Interiors','Remote STR interior design studio','Offers pre-designed rooms, custom design and membership-based support.','Its about page emphasizes remote styling. Confirm any purchasing or on-site labor in the selected service.','States that services can be fully remote. Confirm local execution arrangements separately.','Request terms for the chosen room, custom design or membership service.','What does the membership or custom scope deliver, and who installs the plan?','https://www.ondesigninteriors.co/about-ondesign')
add('turnkey-bnb-design','TurnKey BnB Design','Interior and vacation-rental design studio','Its official site presents interior and vacation-rental design services.','Confirm ordering, receiving and installation responsibilities in the chosen design engagement.','Confirm project and on-site service availability for the specific property.','Request a proposal covering the rooms and execution responsibilities you need.','Does your proposal include on-site setup or a plan for a local team to implement?','https://www.turnkeybnbdesign.com/')
add('hostgpo','HostGPO','Purchasing membership with partner design program','The design program describes complimentary partner design for members.','Lists order tracking, delivery scheduling support and partner shipping options; hands-on and turnkey choices depend on the design option.','Program eligibility lists properties in the contiguous United States.','Partner design is described as complimentary for members; membership, goods and execution costs need confirmation.','Which partner delivers the design and install, and which fees remain beyond complimentary design?','https://www.hostgpo.com/design-program')
add('minoan','Minoan','Hospitality procurement platform','The designer offering focuses on purchasing access and project collaboration rather than selling a standalone interior-design engagement.','Describes ordering logistics and customer support for designers managing furnishing projects.','Confirm shipping and supplier eligibility for the actual property and items.','The reviewed designer page describes joining without membership fees; goods and any hired designer cost extra.','Who is your contracted designer, and who handles assembly and the final on-site setup?','https://minoan.com/who-we-work-with/interior-designers')
MYBNB=dict(slug='mybnbdesign',name='MyBnBDesign',kind='STR interior design service',design='The service overview describes concept development, space planning and rental furnishing design.',execution='The service overview describes procurement and installation support. Confirm the exact project scope in your written proposal.',coverage='Confirm design and on-site execution availability for the property with the team.',pricing='Request an itemized proposal separating service fees, furnishing purchases and site work.',question='Which ordering, delivery, installation and photography tasks are included in our proposal?',source='https://www.mybnbdesign.com/services.html',checked='2026-10-06')
add('j-squared-home-designs','J Squared Home Designs','Interior design and staging studio with vacation-rental service','Its official vacation-rental page offers design for short-term-rental clients.','The linked service document describes design and white-glove turnkey installation. Confirm current scope.','Its official page lists Missouri City, Texas and nearby areas. Confirm rental project coverage.','Request a current vacation-rental proposal and itemized execution costs.','Is the installation service document current for your property and market?','https://j2homedesigns.com/vacation-rental-design/')
add('furnishr','Furnishr','Turnkey home furnishing service with STR packages','Its FAQ offers furnishing packages for Airbnb and short-term rentals.','Describes design, sourcing, shipping coordination and on-site assembly; says painting, flooring and wallpaper installation are excluded.','Confirm furnishing and installation coverage for your address.','Its process describes a package fee covering furniture, design, delivery and assembly. Request an itemized total.','Is the property ready for furniture, or does it need excluded renovation work first?','https://furnishr.com/faq/')
add('acm-interiors','ACM Interiors','Interior design studio with turnkey vacation-rental service','Its turnkey page describes furnishing and styling vacation-rental properties.','Presents a managed end-to-end furnishing service. Confirm receiving, installation and handoff tasks.','The site is presented as a Florida Keys interior design studio. Confirm the property location directly.','Request a project-specific turnkey design and furnishing quote.','Which site visits and execution tasks are included for the property location?','https://www.acminteriors.com/turnkey-design')
assert len(COMPANIES)==23
