"""Render the reviewed, provider-neutral comparison batch and its discovery links."""
from pathlib import Path
from html import escape as h
import json
import xml.etree.ElementTree as E
ROOT=Path(__file__).resolve().parents[1]
BASE='https://www.mybnbdesign.com'
# slug, title, decision context, option A, option B, three dimensions, scenario, quote questions
GUIDES=[
('full-service-vs-design-only','Full-service vs design-only STR furnishing','Choose how much of the furnishing project you want to manage yourself. A room plan and shopping list do not automatically include purchasing, receiving or installation.','Full-service engagement','Design-only engagement',[
('Responsibility','Can combine design, procurement and installation when each is explicitly contracted.','Usually leaves ordering, assembly and delivery coordination with the host.'),('Control','Requires approval gates before orders and a named person handling substitutions.','Gives the host direct purchasing control and responsibility for implementing the plan.'),('Capacity','Useful when the property is remote or the host cannot coordinate multiple deliveries.','Useful when the host has reliable local help and time to manage execution.')],
'A remote owner preparing a three-bedroom rental has a cleaner but no receiving team. A design-only fee may look attractive until delivery storage, assembly and packaging removal are added. Request both scopes against the same room list before selecting one.',
['Who receives goods and checks damage before the return window closes?','Are installation, packaging removal and final styling included?','What happens if an approved item becomes unavailable?']),
('remote-vs-local-designer','Remote vs local interior design for a rental','Compare the need for physical site access with the quality of your measurements, photos and local execution team. Location alone does not establish rental experience.','Remote designer','Local designer',[
('Site information','Depends on accurate measurements, walkthrough footage and a local contact.','May offer site visits; verify their frequency and what is measured.'),('Implementation','Needs a clear handoff to the person placing furniture and resolving fit problems.','Can coordinate site work if that service is included, rather than assumed.'),('Selection','Allows evaluation beyond the immediate area, including relevant portfolios.','Can be convenient for inspecting existing pieces and local supplier options.')],
'A narrow stairwell determines whether a sofa can reach the upstairs living room. Either designer needs the full delivery path, not just the room dimensions. The local option is helpful if the host cannot obtain those measurements; the remote option can work with a competent site contact.',
['Who measures doorways, stairs and clearance?','How are site discrepancies and change orders handled?','Is a post-installation review included?']),
('furniture-package-vs-custom-plan','Furniture package vs custom furnishing plan','Compare a predetermined bundle with a room-by-room plan built around your property. Evaluate the exact included inventory and measurements rather than the number of pieces advertised.','Furniture package','Custom furnishing plan',[
('Fit','Requires checking every major item against actual room and delivery dimensions.','Can select sizes and quantities around circulation and guest capacity.'),('Ordering','May simplify selection but still requires a written delivery and substitution policy.','Can involve more vendors and delivery coordination.'),('Completeness','May exclude lighting, kitchen inventory, linens or outdoor pieces.','Can cover those categories when they are included in the scope.')],
'A package contains a dining table for four while the listing is planned for six guests. Adding two chairs does not solve inadequate table space. Compare complete seating, sleeping and storage needs before calculating a package saving.',
['Can items be removed or resized, and how does that affect price?','Which categories are excluded from the package?','Who approves substitutions and verifies dimensions?']),
('new-vs-secondhand-furniture','New vs secondhand furniture for a short-term rental','Use acquisition cost, inspection effort and replacement needs to decide where secondhand pieces make sense. A low purchase price can be offset by transport, cleaning and repair.','New furniture','Secondhand furniture',[
('Condition','Review product specifications, return terms and warranty exclusions.','Inspect joints, odors, upholstery, hardware and missing parts before purchase.'),('Repeatability','Check whether the model and spare parts are likely to remain available.','Matching replacements may be difficult for one-off finds.'),('Logistics','Track shipping charges, lead times and assembly.','Plan pickup, access, lifting help and any necessary restoration.')],
'A host finds a used solid-wood dresser locally but needs identical bedside lamps in four rooms. A mixed approach can use the inspected dresser while buying repeatable lighting. Compare each item category separately instead of imposing one purchasing rule on the entire property.',
['Can the item be inspected before payment?','What are the all-in pickup, repair and cleaning costs?','Can damaged components be replaced?']),
('performance-fabric-vs-leather','Performance fabric vs leather rental sofas','Compare documented cleaning instructions, comfort and repair options for the actual sofa model. Material labels alone do not predict how a product will hold up in your property.','Performance fabric','Leather upholstery',[
('Cleaning','Read the fabric cleaning code and approved products; test cleaning on a hidden area.','Follow the specified leather care instructions and avoid assuming every surface tolerates the same cleaner.'),('Damage','Check removable covers, cushion availability and treatment limitations.','Evaluate scratching, finish wear and whether a repair specialist can service the finish.'),('Comfort','Consider weave, texture and drying time after cleaning.','Consider surface temperature, feel and the local climate.')],
'A pet-friendly rental prioritizes replaceable cushion covers, while a compact city apartment needs a sofa that can be cleaned between short stays. Ask for model-specific care and repair information for both materials, then choose based on the turnover team’s capabilities.',
['What cleaning products and methods are approved?','Are replacement cushions or covers sold separately?','What damage and commercial use are excluded from the warranty?']),
('washable-rugs-vs-traditional-rugs','Washable vs traditional rugs in vacation rentals','Choose a rug by the room, turnover workflow and cleaning equipment available. Washable does not mean a large rug will fit the machine at your property.','Washable rug system','Traditional area rug',[
('Cleaning workflow','Verify capacity requirements, drying instructions and spare-cover availability.','Arrange spot treatment and periodic deeper cleaning suitable for the fiber.'),('Installation','Check pad compatibility, edges and how the cover is reattached after washing.','Check backing, pad requirements and movement on the actual floor.'),('Turnover','Allow time for washing, drying and resetting, or keep a spare.','Plan how a stained rug is removed or cleaned before the next arrival.')],
'A host chooses a large washable rug but uses a small stacked washer. If the manufacturer requires a larger machine, off-site laundry and transport become part of the cost. A smaller washable rug or a different living-room solution may fit the operation better.',
['Will this size fit the available washer and dryer?','What pad is suitable for the floor finish?','How will the room be reset while the rug is being cleaned?']),
('sleeper-sofa-vs-dedicated-bed','Sleeper sofa vs dedicated guest bed','Compare the nightly guest experience with the space needed during the day and at bedtime. A theoretical extra sleeping position is useful only when guests can access it comfortably.','Sleeper sofa','Dedicated bed',[
('Floor plan','Measure the fully opened bed plus the route to exits and bathrooms.','Reserve permanent sleeping space and appropriate circulation.'),('Turnover','Specify how bedding is stored and whether the mechanism is checked between stays.','Makes the sleeping surface consistently accessible for making and inspection.'),('Guest use','Requires clear setup instructions and consideration of shared-room privacy.','Provides a ready sleeping space, subject to the room layout and amenities.')],
'A studio can fit a sleeper sofa when closed but loses the bathroom route when opened. Draw both layouts before selecting furniture. If safe circulation cannot be maintained, the property should not rely on that position to support its advertised guest capacity.',
['What are the fully opened dimensions?','Where do pillows and bedding live during the day?','Can guests reach the bathroom without climbing around furniture?']),
('matching-bedroom-sets-vs-mixed-furniture','Matching bedroom sets vs mixed furniture','Choose between a coordinated set and individually selected pieces based on room dimensions, storage and future replacement needs. Visual consistency does not require every piece to come from one collection.','Matching bedroom set','Mixed furniture plan',[
('Room fit','A bundled dresser or nightstand may be the wrong size even if the bed fits.','Lets each item respond to the room’s specific dimensions.'),('Coordination','Simplifies finish decisions, but check actual samples and stock.','Requires a deliberate palette, scale and repeated details.'),('Replacement','Determine whether individual pieces can be purchased separately later.','Document dimensions and finishes so a replacement can fit the existing scheme.')],
'A bedroom has room for a queen bed but only one full-size nightstand. A package with two wide nightstands creates a circulation problem. Mixing a standard nightstand with a compact shelf can provide bedside functionality without forcing the package footprint.',
['Can pieces be purchased individually?','Do drawers open without hitting adjacent furniture?','What finishes and dimensions should a replacement match?']),
('diy-installation-vs-professional-installation','DIY vs professional furniture installation','Compare available labor, tools, delivery access and the complexity of the item list. Installation includes more than assembling the biggest pieces.','Host-managed installation','Professional installation team',[
('Preparation','Host schedules deliveries, counts parts and organizes tools and labor.','Confirm receiving, inventory and missing-item reporting are included.'),('Execution','Works when capable help and adequate time are available.','Request a room placement plan and a written list of tasks.'),('Closeout','Host handles packaging, product checks and punch-list work.','Confirm waste removal, damage documentation and callbacks in the contract.')],
'A property receives beds, desks and outdoor furniture on different days. A one-day installation quote may require everything to be on site beforehand. If the delivery schedule is uncertain, price storage and a second visit before comparing the two approaches.',
['Is delivery receiving part of the installation price?','Who handles wall attachment and specialist work?','What is the process for missing hardware or damaged goods?']),
('full-refresh-vs-room-by-room-upgrade','Full property refresh vs room-by-room upgrades','Choose the project sequence around the condition of existing furniture, available cash and scheduling. Prioritize functional defects before decorative improvements.','Full property refresh','Room-by-room upgrades',[
('Coordination','Can align the entire palette and inventory in one project.','Needs a master plan to avoid incompatible future purchases.'),('Scheduling','Requires a realistic procurement and installation window.','Allows smaller work blocks, while tracking disruption across multiple visits.'),('Budget control','Collect an itemized total and reserve for unresolved conditions.','Assign each phase a cap and avoid repeating shipping or labor unnecessarily.')],
'A rental has sound bedroom furniture but an uncomfortable sofa and inadequate dining seating. Replacing everything may consume funds needed for those functional gaps. A room-by-room plan can begin with living and dining while preserving an overall palette for later bedrooms.',
['Which existing items can remain after inspection?','What costs repeat when work is split into phases?','What must be complete before the next guest arrival?']),
('statement-design-vs-neutral-design','Statement design vs neutral rental interiors','Compare visual identity with maintenance, lighting and the rest of the property. Neither approach guarantees bookings; choose a plan that works in person as well as in listing photos.','Statement design','Neutral design',[
('Visual direction','Uses a strong focal point, color or themed detail with a controlled supporting palette.','Uses quieter colors and forms; needs texture and lighting to avoid a flat result.'),('Maintenance','Document specialty finishes and unique replacement pieces.','Record exact paint codes and fabric specifications; neutral items can still mismatch.'),('Photography','Check how strong colors and focal points appear under actual light.','Check contrast so furniture does not disappear against walls.')],
'A small living room can support a distinctive art wall without using bold treatments on every surface. A neutral base with one planned focal point offers another option. Test samples and photograph the proposed arrangement before ordering the complete room.',
['What is the primary focal point in each room?','How will replacement pieces preserve the palette?','Have paint and fabric samples been checked under day and evening lighting?']),
('pre-launch-design-vs-post-launch-redesign','Pre-launch furnishing vs redesigning an operating rental','Compare preparing the complete property before opening with improving a property that already hosts guests. The latter needs a work schedule that fits actual reservations and access.','Pre-launch furnishing','Redesign of an operating rental',[
('Information','Start with measurements, target guest needs and a complete inventory.','Use observed wear, guest feedback and maintenance records to define priorities.'),('Scheduling','Coordinate delivery, installation, cleaning and photography before opening.','Plan work blocks with the host or manager and resolve storage between visits.'),('Documentation','Create care instructions, product records and room photos at handoff.','Update inventory, listing photos and guest instructions after each meaningful change.')],
'A booked property needs new dining chairs, but the replacement shipment is split. Removing existing seating too early creates a service gap. Keep a workable room until the complete replacement is received, inspected and ready to install during an agreed access window.',
['Who confirms that the property is ready for guests after installation?','Where will deliveries be stored during occupied periods?','Which photos and guest instructions must be updated after the change?'])
]
CSS='''body{margin:0;background:#fbf8f3;color:#282c29;font:17px/1.7 system-ui,sans-serif}header,main,footer{max-width:1040px;margin:auto;padding:24px}header{display:flex;gap:20px;flex-wrap:wrap;border-bottom:1px solid #ddd}a{color:#355746;text-underline-offset:4px}h1{font:clamp(30px,5vw,52px)/1.15 Georgia,serif;max-width:850px}h2{font:28px/1.3 Georgia,serif;margin-top:36px}.label{letter-spacing:.1em;text-transform:uppercase;font-size:12px}.table-wrap{overflow-x:auto}table{border-collapse:collapse;width:100%;min-width:650px}th,td{text-align:left;vertical-align:top;padding:16px;border:1px solid #d8ddd6}th{background:#e8ede7}.example{padding:24px;background:#e8ede7;border-left:4px solid #355746}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:20px}.cards article{padding:20px;border:1px solid #ddd;background:white}.cta{display:inline-block;padding:12px 20px;background:#355746;color:white;border-radius:5px}footer{border-top:1px solid #ddd;font-size:14px}a:focus-visible{outline:3px solid #ad772b;outline-offset:4px}'''
(ROOT/'assets/comparison-guides.css').write_text(CSS+'\n')
def page(title,desc,route,body):
 schema={'@context':'https://schema.org','@type':'WebPage','name':title,'description':desc,'url':BASE+route,'dateModified':'2026-10-06','publisher':{'@type':'Organization','name':'MyBnBDesign','url':BASE+'/'}}
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+h(title)+' | MyBnBDesign</title><meta name="description" content="'+h(desc,quote=True)+'"><link rel="canonical" href="'+BASE+route+'"><meta property="og:title" content="'+h(title,quote=True)+'"><meta property="og:description" content="'+h(desc,quote=True)+'"><meta property="og:url" content="'+BASE+route+'"><meta property="og:type" content="website"><link rel="stylesheet" href="/assets/comparison-guides.css"><script type="application/ld+json">'+json.dumps(schema)+'</script></head><body><header><a href="/">MyBnBDesign</a><nav aria-label="Main"><a href="/services.html">Services</a> · <a href="/compare/">Comparisons</a> · <a href="/resources/">Planning resources</a></nav></header><main>'+body+'</main><footer>Published by MyBnBDesign. Use the same scope questions when evaluating our proposal or another provider. <a href="/contact.html">Contact us</a>.</footer></body></html>\n'
for i,(slug,title,intro,a,b,rows,example,questions) in enumerate(GUIDES):
 route='/compare/'+slug+'/'
 table='<div class="table-wrap" role="region" aria-label="Comparison table" tabindex="0"><table><caption>Compare the practical tradeoffs</caption><thead><tr><th scope="col">Decision</th><th scope="col">'+h(a)+'</th><th scope="col">'+h(b)+'</th></tr></thead><tbody>'+''.join('<tr><th scope="row">'+h(k)+'</th><td>'+h(x)+'</td><td>'+h(y)+'</td></tr>' for k,x,y in rows)+'</tbody></table></div>'
 related=[GUIDES[(i+1)%len(GUIDES)],GUIDES[(i+4)%len(GUIDES)]]
 body='<p class="label">Rental furnishing comparison · Updated October 6, 2026</p><h1>'+h(title)+'</h1><p>'+h(intro)+'</p><h2>What changes between the options?</h2>'+table+'<h2>A property scenario</h2><p class="example">'+h(example)+'</p><h2>Questions to resolve before committing</h2><ul>'+''.join('<li>'+h(q)+'</li>' for q in questions)+'</ul><h2>Compare the complete project cost</h2><p>Put both options against the same rooms, guest capacity and completion date. List product costs, design fees, shipping, receiving, assembly, installation and any repeat visits separately. Assign a person to each task and document exclusions. A lower quoted fee is only comparable when the responsibilities and deliverables match.</p><h2>Apply this to your MyBnBDesign proposal</h2><p>Review our <a href="/services.html">service overview</a>, then ask for a written scope for your actual property. Confirm which tasks are included, who handles site access and how approvals work before ordering. The distinctions above describe project approaches; they do not promise that every provider offers every task.</p><p><a class="cta" href="/book/">Discuss your furnishing project</a></p><h2>Continue comparing</h2><ul>'+''.join('<li><a href="/compare/'+r[0]+'/">'+h(r[1])+'</a></li>' for r in related)+'</ul><p><a href="/compare/">See all design and furnishing comparisons</a></p>'
 target=ROOT/route.lstrip('/')/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(page(title,intro,route,body))
# Preserve existing hub content while adding an explicitly bounded section.
hub=ROOT/'compare/index.html';s=hub.read_text();start='<!-- comparison-guides:start -->';end='<!-- comparison-guides:end -->'
section=start+'<section aria-labelledby="project-comparisons"><h2 id="project-comparisons">Compare project scope, furniture and launch decisions</h2><p>These practical guides compare approaches and materials. Each includes tradeoffs, a property scenario and questions to ask before committing.</p><div class="cards">'+''.join('<article><h3><a href="/compare/'+g[0]+'/">'+h(g[1])+'</a></h3><p>'+h(g[2])+'</p></article>' for g in GUIDES)+'</div></section>'+end
if start in s:s=s[:s.index(start)]+section+s[s.index(end)+len(end):]
else:s=s.replace('<h2>Compare the written scope',section+'<h2>Compare the written scope')
if '/assets/comparison-guides.css' not in s:s=s.replace('</head>','<link rel="stylesheet" href="/assets/comparison-guides.css"></head>')
hub.write_text(s)
ns='http://www.sitemaps.org/schemas/sitemap/0.9';E.register_namespace('',ns);tree=E.parse(ROOT/'sitemap.xml');root=tree.getroot();existing={x.text for x in root.findall('{'+ns+'}url/{'+ns+'}loc')}
for route in ['/compare/']+['/compare/'+g[0]+'/' for g in GUIDES]:
 url=BASE+route
 if url not in existing:
  row=E.SubElement(root,'{'+ns+'}url');E.SubElement(row,'{'+ns+'}loc').text=url
 else:row=next(x for x in root if x.find('{'+ns+'}loc').text==url)
 mod=row.find('{'+ns+'}lastmod')
 if mod is None:mod=E.SubElement(row,'{'+ns+'}lastmod')
 mod.text='2026-10-06'
E.indent(tree);tree.write(ROOT/'sitemap.xml',encoding='utf-8',xml_declaration=True)
print('Rendered',len(GUIDES),'comparison guides and updated hub/sitemap')
