"""Render researched STR provider comparisons and rebuild their discovery.
Provider facts are centralized in content/str_design_companies.py.
"""
from pathlib import Path
from itertools import combinations
from html import escape as h
import json,re,sys,xml.etree.ElementTree as E
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from content.str_design_companies import COMPANIES,MYBNB
BASE='https://www.mybnbdesign.com';DATE='2026-10-06';ROUTES=[];MANIFEST=[]
ALT_EXISTING={'str-cribs':'strcribs-alternative','showplace':'showplace-alternative','somerled-designs':'somerled-alternative','bee-setups':'bee-setups-alternative','vacay-rental-design':'vacay-rental-design-alternative'}
def alt(c):return '/alternatives/'+ALT_EXISTING.get(c['slug'],c['slug']+'-alternative')+'/'
def route(a,b):
 if a['slug']=='mybnbdesign' and b['slug'] in ('hostgpo','minoan'):return '/compare/mybnbdesign-vs-'+b['slug']+'.html'
 return '/compare/companies/'+a['slug']+'-vs-'+b['slug']+'/'
def link(u,t):return '<a href="'+h(u,quote=True)+'">'+h(t)+'</a>'
def page(title,desc,url,body,crumbs):
 schema=[{'@context':'https://schema.org','@type':'WebPage','name':title,'description':desc,'url':BASE+url,'dateModified':DATE,'publisher':{'@type':'Organization','name':'MyBnBDesign','url':BASE+'/'}},{'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':i+1,'name':n,'item':BASE+u} for i,(n,u) in enumerate(crumbs)]}]
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+h(title)+'</title><meta name="description" content="'+h(desc,quote=True)+'"><link rel="canonical" href="'+BASE+url+'"><meta property="og:title" content="'+h(title,quote=True)+'"><meta property="og:description" content="'+h(desc,quote=True)+'"><meta property="og:url" content="'+BASE+url+'"><meta property="og:type" content="website"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="/assets/str-company-library.css"><script type="application/ld+json">'+json.dumps(schema)+'</script><script defer src="/assets/str-company-library.js"></script></head><body><header>'+link('/','MyBnBDesign')+'<nav aria-label="Main">'+link('/services.html','Services')+' · '+link('/compare/companies/','Company comparisons')+' · '+link('/alternatives/str-design-companies/','STR designers')+'</nav></header><main><nav aria-label="Breadcrumb">'+' / '.join(link(u,n) for n,u in crumbs[:-1])+'</nav>'+body+'</main><footer>Published by MyBnBDesign, a service provider in this category. Facts summarize provider-authored pages checked October 6, 2026. Confirm current offers directly. '+link('/contact.html','Contact us')+'.</footer></body></html>\n'
def write(url,text,kind,keyword,priority='candidate',evidence='Provider verified; individual query demand unmeasured'):
 f=ROOT/url.lstrip('/')
 if url.endswith('/'):f=f/'index.html'
 f.parent.mkdir(parents=True,exist_ok=True);f.write_text(text);ROUTES.append(url)
 MANIFEST.append(dict(route=url,type=kind,primary_keyword=keyword,priority=priority,evidence=evidence,search_volume='unavailable',keyword_difficulty='unavailable',current_rank='unavailable'))
def source(c):return link(c['source'],c['name']+' official service information')
def facts(c):
 return '<dl>'+''.join('<dt>'+label+'</dt><dd>'+h(c[key])+'</dd>' for key,label in [('kind','Service model'),('design','Design deliverables'),('execution','Execution'),('coverage','Location and eligibility'),('pricing','Cost and proposal')])+'</dl><p>'+source(c)+'</p>'
def worksheet(a,b):
 out='<section class="worksheet" aria-labelledby="worksheet-title"><h2 id="worksheet-title">Compare the complete proposals</h2><p>Enter quoted amounts in the same currency. Include tax in an appropriate field if it applies. Blank fields count as zero; totals cover only the entered costs. An unquoted item is an open question, not evidence that a provider is cheaper. Entries remain only until this page is reloaded.</p><div class="quote-grid">'
 for key,c in [('a',a),('b',b)]:
  out+='<fieldset><legend>'+h(c['name'])+'</legend>'
  for field,label in [('design','Design and service fee'),('goods','Furniture and essentials'),('delivery','Shipping, receiving and storage'),('install','Installation, travel and other costs')]:
   ident=key+'-'+field;out+='<label for="'+ident+'">'+label+'</label><input id="'+ident+'" data-quote="'+key+'" type="number" min="0" step="0.01" inputmode="decimal" placeholder="0">'
  out+='<p><strong>Entered total: <output id="total-'+key+'">0.00</output></strong></p><label for="notes-'+key+'">Proposal link, exclusions and unresolved items</label><textarea id="notes-'+key+'" rows="3"></textarea></fieldset>'
 return out+'</div><p id="cost-result" role="status" aria-live="polite">Enter complete quoted costs to compare.</p><button type="button" id="print-comparison">Print comparison and notes</button></section>'
PROVIDERS=[MYBNB]+COMPANIES;PAIRS=list(combinations(PROVIDERS,2))
for a,b in PAIRS:
 url=route(a,b);name=a['name']+' vs '+b['name'];title=name+' | STR design comparison'
 description='Compare '+a['name']+' and '+b['name']+': published STR services, execution, coverage, costs and questions for your proposals.'
 rows=''.join('<tr><th scope="row">'+lab+'</th><td>'+h(a[key])+'</td><td>'+h(b[key])+'</td></tr>' for key,lab in [('kind','Service model'),('design','Design'),('execution','Procurement and setup'),('coverage','Coverage to confirm'),('pricing','Cost information')])
 distinction='Compare the exact contracted package rather than choosing from the company name. The published service models are '+a['kind'].lower()+' and '+b['kind'].lower()+'.'
 if a['slug'] in ('hostgpo','minoan') or b['slug'] in ('hostgpo','minoan'):
  distinction+=' A purchasing platform or partner program can be used alongside an independent designer; it is not automatically a replacement for a design-and-installation contract.'
 body='<p class="label">STR design companies · Source check October 6, 2026</p><h1>'+h(name)+'</h1><p>Choosing between '+h(a['name'])+' and '+h(b['name'])+' for an Airbnb or vacation rental? '+h(distinction)+'</p><p>This comparison is published by MyBnBDesign. It reports advertised services, not independently tested performance or a universal winner.</p><h2>Published services at a glance</h2><div class="table-wrap" role="region" aria-label="Company comparison" tabindex="0"><table><caption>'+h(name)+' service scope</caption><thead><tr><th scope="col">Question</th><th scope="col">'+h(a['name'])+'</th><th scope="col">'+h(b['name'])+'</th></tr></thead><tbody>'+rows+'</tbody></table></div><p>Sources: '+source(a)+' · '+source(b)+'. Starting fees are snapshots of the cited offers, not complete furnishing budgets. An unspecified item is unconfirmed, not unavailable.</p>'
 body+='<h2>Resolve the questions that change this comparison</h2><h3>Ask '+h(a['name'])+'</h3><p>'+h(a['question'])+'</p><h3>Ask '+h(b['name'])+'</h3><p>'+h(b['question'])+'</p><p>Send the same property brief to both: address, floor plan, room list, intended guest capacity, existing furniture to retain and your desired completion window. Ask each team to identify what they need from your local contact before quoting. This makes differences in service scope visible before a design fee is compared with a complete installation budget.</p>'
 body+=worksheet(a,b)
 body+='<h2>Decide from the written deliverables</h2><ol><li>Confirm property eligibility and whether the proposal is remote design, furnishing procurement or on-site delivery and setup.</li><li>Check the design handoff: scaled layouts, item specifications, revisions and approval steps. A shopping list and installed room are different deliverables.</li><li>Assign ordering, receiving, damage claims, substitutions, assembly and cleanup to a named person. Record travel, storage and additional visit costs.</li><li>Get a dated completion plan and a final punch-list process. Treat advertised timelines as estimates until the property scope and inventory are confirmed.</li></ol><p>Use '+link('/resources/guides/quote-scope-comparison/','the furnishing quote scope worksheet')+' for the shared brief and '+link('/compare/full-service-vs-design-only/','the full-service versus design-only guide')+' to clarify how much execution you want to manage.</p>'
 related=[(x,y) for x,y in PAIRS if (x==a or y==a or x==b or y==b) and (x,y)!=(a,b)][:4]
 body+='<h2>Related company comparisons</h2><ul>'+''.join('<li>'+link(route(x,y),x['name']+' vs '+y['name'])+'</li>' for x,y in related)+'</ul><p>'+link(alt(a),'Alternatives to '+a['name'])+' · '+link(alt(b),'Alternatives to '+b['name'])+'</p>' if a!=MYBNB else '<h2>Continue your shortlist</h2><p>'+link(alt(b),b['name']+' alternatives and service questions')+' · '+link('/compare/companies/','All STR company comparisons')+'</p>'
 body+='<h2>Include MyBnBDesign in your shortlist</h2><p>Review '+link('/services.html','our published service scope')+' and '+link('/portfolio.html','portfolio')+', then request an itemized proposal for the same property brief. Ask us the same coverage, cost and execution questions. Provider outcome claims and testimonials do not establish what your property will earn.</p><p><a class="cta" href="/book/">Discuss your STR design project</a></p>'
 primary=a==MYBNB or {a['slug'],b['slug']}=={'showplace','somerled-designs'}
 evidence='Direct brand comparison; commercial intent inferred; demand unmeasured'
 if {a['slug'],b['slug']}=={'showplace','somerled-designs'}:evidence='Provider-published comparison observed in public search; volume and ranking unmeasured'
 write(url,page(title,description,url,body,[('Home','/'),('Company comparisons','/compare/companies/'),(name,url)]),'company comparison',name.lower(), 'first wave' if primary else 'candidate',evidence)
for c in COMPANIES:
 url=alt(c);name=c['name']+' alternatives for STR design'
 # Deliberately shortlist a few distinct service models, rather than repeating all providers.
 recommendations=[MYBNB]+[x for x in COMPANIES if x!=c and x['slug'] in ('showplace','somerled-designs','str-cribs','amenistays')][:3]
 body='<p class="label">Verified provider directory · October 6, 2026</p><h1>'+h(name)+'</h1><p>Build an alternative shortlist around the work you want to hand off. '+h(c['name'])+' describes its offering as a '+h(c['kind'].lower())+'. Review its published deliverables before comparing it with a remote plan, procurement program or complete installation engagement.</p><h2>What '+h(c['name'])+' publishes</h2>'+facts(c)+'<h2>The question to clarify first</h2><p>'+h(c['question'])+'</p><p>Give each candidate the same room inventory, measurements, retained items and desired launch window. A provider may be appropriate for one service tier and a poor match for another, so obtain the exact package and location eligibility before making a decision.</p><h2>Alternatives to include in your shortlist</h2><div class="cards">'+''.join('<article><h3>'+h(x['name'])+'</h3><p>'+h(x['kind'])+'. '+h(x['design'])+'</p><p>'+link(route(MYBNB,c) if x==MYBNB else route(*next((a,b) for a,b in PAIRS if {a['slug'],b['slug']}=={c['slug'],x['slug']})),x['name']+' vs '+c['name'])+'</p></article>' for x in recommendations)+'</div><h2>Compare a complete proposal</h2><ul><li>Separate design fees, furnishing purchases, freight, receiving, installation and travel.</li><li>Ask who approves substitutions and what happens when an item is damaged or delayed.</li><li>Clarify how design revisions, site visits, photo staging and handoff are billed.</li><li>Confirm whether the offered scope includes your property type and market.</li></ul><p>Published starting fees are useful for an initial conversation but are not a complete property budget. Compare written deliverables rather than expecting all providers to price the same scope. Use '+link('/resources/guides/quote-scope-comparison/','the quote scope worksheet')+' to keep responsibilities and exclusions visible.</p><h2>Explore all comparisons involving '+h(c['name'])+'</h2><ul>'+''.join('<li>'+link(route(a,b),a['name']+' vs '+b['name'])+'</li>' for a,b in PAIRS if c in (a,b))+'</ul><h2>How we selected these alternatives</h2><p>The listed services have public STR or furnishing offerings reviewed for this directory. This is a service-scope shortlist, not a rating, independent review or assertion that one company is best. MyBnBDesign publishes the directory and is included as a candidate. Provider offers and coverage can change; confirm current terms directly.</p><p>'+link('/alternatives/str-design-companies/','Browse researched STR design companies')+' · '+link('/book/','Request a MyBnBDesign proposal')+'</p>'
 write(url,page(name+' | MyBnBDesign','Compare '+c['name']+' alternatives using official service information, execution responsibilities and proposal questions for rental owners.',url,body,[('Home','/'),('STR design companies','/alternatives/str-design-companies/'),(c['name']+' alternatives',url)]),'alternatives',c['name'].lower()+' alternatives','first wave')
# Directory and intent hubs provide clean discovery and keep platforms distinguished.
company_cards=''.join('<article data-company><h2>'+link(alt(c),c['name'])+'</h2><p>'+h(c['kind'])+'</p><p>'+h(c['design'])+'</p><p>'+link(route(MYBNB,c),'Compare with MyBnBDesign')+' · '+source(c)+'</p></article>' for c in COMPANIES)
url='/alternatives/str-design-companies/'
body='<p class="label">Research-backed service directory</p><h1>STR design companies and furnishing services</h1><p>Explore 21 design and setup providers plus two adjacent procurement and partner-program options. Use the service model and written scope to shortlist companies for your property. Inclusion is based on official published services, not paid placement or a performance ranking.</p><label for="company-search">Find a company or service model</label><input id="company-search" type="search" placeholder="Try Showplace, virtual or turnkey"><p id="company-count" role="status" aria-live="polite">23 providers</p><div id="company-results" class="cards">'+company_cards+'</div><p id="no-companies" hidden>No providers match. Try another company name or service term.</p><h2>Start with the scope you need</h2><p>'+link('/compare/companies/virtual-design/','Virtual design candidates')+' · '+link('/compare/companies/turnkey-design/','Turnkey design candidates')+' · '+link('/compare/companies/','Company comparison library')+'</p><p>HostGPO is a purchasing membership with a partner design program. Minoan is a procurement platform serving designers. Both may support a furnishing project alongside a contracted design team.</p>'
write(url,page('STR design companies: 23 researched providers | MyBnBDesign','Find short-term-rental design companies, turnkey furnishing services and virtual designers. Compare official services and request matching proposals.',url,body,[('Home','/'),('STR design companies',url)]),'directory','str design companies','first wave','Broad category and provider comparison results observed; demand unmeasured')
for key,title,slugs,intro in [
 ('virtual-design','Virtual STR design companies',['somerled-designs','str-refresh','magic-interiors','becky-jones','the-nested-company','amenistays','michael-interieurs','erica-ooh-designs','on-design-interiors'],'These providers publish remote design or owner-implemented plans. Confirm exactly what is delivered and who handles local measurements, buying, receiving and installation.'),
 ('turnkey-design','Turnkey STR design and furnishing companies',['showplace','somerled-designs','str-refresh','magic-interiors','belo-home-styling','bee-setups','becky-jones','the-nested-company','vacay-rental-design','sol-vibe-design','amenistays','michael-interieurs','erica-ooh-designs','turnkey-bnb-design','j-squared-home-designs','furnishr','acm-interiors'],'These providers describe installation, setup or managed furnishing options. Turnkey is a scope label: confirm the room inventory, coverage, subcontractors and exclusions in the actual proposal.')]:
 url='/compare/companies/'+key+'/';candidates=[c for c in COMPANIES if c['slug'] in slugs]
 body='<p class="label">Shortlist by scope</p><h1>'+h(title)+'</h1><p>'+h(intro)+'</p><div class="cards">'+''.join('<article><h2>'+link(alt(c),c['name'])+'</h2><p>'+h(c['design'] if key=='virtual-design' else c['execution'])+'</p><p>'+source(c)+' · '+link(route(MYBNB,c),'Compare with MyBnBDesign')+'</p></article>' for c in candidates)+'</div><h2>Request matching proposals</h2><p>Send a common floor plan and inventory to each candidate. Separate service fees, furnishings, delivery, receiving, installation and travel. Record who owns final measurements, substitution approvals and the punch list.</p><p>'+link('/compare/full-service-vs-design-only/','Compare plan-only and managed execution')+' · '+link('/alternatives/str-design-companies/','All researched providers')+'</p>'
 write(url,page(title+' | MyBnBDesign',intro,url,body,[('Home','/'),('Company comparisons','/compare/companies/'),(title,url)]),'service shortlist',title.lower(),'first wave')
url='/compare/companies/'
body='<p class="label">STR provider decision library</p><h1>Compare STR design companies</h1><p>Compare 276 pairs involving MyBnBDesign and 23 researched providers. Each comparison cites official service information and includes property-specific questions and a worksheet for the actual proposals. Search demand has not been measured for every pair; this library helps you evaluate a shortlist.</p><p>'+link('/alternatives/str-design-companies/','Browse all researched companies')+' · '+link('/compare/companies/virtual-design/','Virtual design')+' · '+link('/compare/companies/turnkey-design/','Turnkey design')+'</p><h2>Compare MyBnBDesign with your shortlisted provider</h2><div class="cards">'+''.join('<article><h3>'+link(route(MYBNB,c),'MyBnBDesign vs '+c['name'])+'</h3><p>'+h(c['kind'])+'</p></article>' for c in COMPANIES)+'</div><h2>Search all company comparisons</h2><label for="comparison-search">Company names</label><input id="comparison-search" type="search" placeholder="Try Showplace Somerled"><p id="search-count" role="status" aria-live="polite">276 comparisons</p><div id="comparison-results" class="cards">'+''.join('<article data-comparison><h3>'+link(route(a,b),a['name']+' vs '+b['name'])+'</h3><p>'+h(a['kind'])+' / '+h(b['kind'])+'</p></article>' for a,b in PAIRS)+'</div><p id="no-comparisons" hidden>No comparisons match. Try one company name.</p>'
write(url,page('STR design company comparisons | MyBnBDesign','Compare MyBnBDesign, Showplace, STR Cribs, Somerled, Bee Setups and other rental design services using cited scope, costs and execution details.',url,body,[('Home','/'),('Company comparisons',url)]),'comparison hub','str design company comparisons','first wave')
# Stable insertion blocks keep regeneration deterministic and preserve unrelated content.
for path in ['compare/index.html','alternatives/index.html']:
 f=ROOT/path;s=f.read_text();start='<!-- STR_COMPANY_LIBRARY:start -->';end='<!-- STR_COMPANY_LIBRARY:end -->'
 block=start+'<section><h2>'+link('/alternatives/str-design-companies/','Research real STR design companies')+'</h2><p>Browse 23 verified provider offerings, including Showplace, STR Cribs, Somerled Designs, Bee Setups, Magic Interiors and specialist studios. Compare complete service scopes and ask for current proposals.</p><p>'+link('/compare/companies/','Explore company comparisons')+' · '+link('/compare/companies/virtual-design/','Virtual design providers')+' · '+link('/compare/companies/turnkey-design/','Turnkey furnishing providers')+'</p></section>'+end
 if start in s:s=s[:s.index(start)]+block+s[s.index(end)+len(end):]
 else:s=s.replace('</main>',block+'</main>')
 f.write_text(s)
ns='http://www.sitemaps.org/schemas/sitemap/0.9';E.register_namespace('',ns);tree=E.parse(ROOT/'sitemap.xml');root=tree.getroot();known={r.find('{'+ns+'}loc').text:r for r in root}
for url in ROUTES+['/compare/','/alternatives/']:
 full=BASE+url;row=known.get(full)
 if row is None:row=E.SubElement(root,'{'+ns+'}url');E.SubElement(row,'{'+ns+'}loc').text=full
 mod=row.find('{'+ns+'}lastmod')
 if mod is None:mod=E.SubElement(row,'{'+ns+'}lastmod')
 mod.text=DATE
E.indent(tree);tree.write(ROOT/'sitemap.xml',encoding='utf-8',xml_declaration=True)
(ROOT/'content/str_company_manifest.json').write_text(json.dumps(MANIFEST,indent=2)+'\n')
print('Rendered',len(PAIRS),'company comparisons,',len(COMPANIES),'alternatives pages, and 4 directories/hubs:',len(ROUTES),'routes')
